<?php

return [
    'categories' => [
        'branding' => [
            'label' => 'Branding & Creative',
            'badge' => 'Creative Service',
            'icon' => 'ri-paint-brush-line',
            'image' => 'portfolio_section.png',
            'hero_kicker' => 'Build a memorable brand that stands out',
            'hero_title' => 'Sharp visuals that make every customer touchpoint feel consistent.',
            'hero_text' => 'From first concepts to final delivery, every asset is prepared for practical use across web, print, and social media.',
            'work_images' => ['portfolio_section.png', 'our_services_2.png', 'hero.png'],
            'process' => ['Discovery', 'Concepts', 'Design', 'Refine', 'Delivery'],
            'metrics' => [
                ['value' => '3X', 'label' => 'Visual Recall'],
                ['value' => '48h', 'label' => 'First Draft'],
                ['value' => '100%', 'label' => 'Source Files'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Starter Creative', 'price' => '$149', 'tag' => 'Launch', 'features' => ['2 design concepts', '2 revision rounds', 'Web-ready files', 'Basic usage guide']],
                ['name' => 'Growth Creative', 'price' => '$299', 'tag' => 'Popular', 'features' => ['4 design concepts', '4 revision rounds', 'Print-ready files', 'Social preview mockup']],
                ['name' => 'Premium Creative', 'price' => '$499', 'tag' => 'Complete', 'features' => ['6 design concepts', 'Full source files', 'Stationery or social kit', 'Priority delivery']],
            ],
        ],
        'web' => [
            'label' => 'Web Solutions',
            'badge' => 'Web Service',
            'icon' => 'ri-global-line',
            'image' => 'our_services.png',
            'hero_kicker' => 'Modern websites built for performance and growth',
            'hero_title' => 'Modern websites built for speed, trust, and customer action.',
            'hero_text' => 'We design clean user journeys, responsive layouts, and practical admin flows that are easy to manage after launch.',
            'work_images' => ['our_services.png', 'hero.png', 'contact_us.png'],
            'process' => ['Plan', 'Wireframe', 'Develop', 'Test', 'Launch'],
            'metrics' => [
                ['value' => '95+', 'label' => 'Speed Score'],
                ['value' => '100%', 'label' => 'Responsive'],
                ['value' => 'SEO', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Starter Website', 'price' => '$399', 'tag' => 'Launch', 'features' => ['Up to 5 pages', 'Responsive design', 'Contact form', 'Basic SEO setup']],
                ['name' => 'Business Website', 'price' => '$899', 'tag' => 'Popular', 'features' => ['Up to 10 pages', 'CMS setup', 'Speed optimization', 'Analytics integration']],
                ['name' => 'Custom Platform', 'price' => '$1,499+', 'tag' => 'Advanced', 'features' => ['Custom features', 'Admin dashboard', 'API integrations', 'Launch support']],
            ],
        ],
        'app' => [
            'label' => 'Mobile Applications',
            'badge' => 'App Service',
            'icon' => 'ri-smartphone-line',
            'image' => 'our_services_2.png',
            'hero_kicker' => 'Powerful mobile experiences for every platform',
            'hero_title' => 'App experiences shaped around simple flows and repeat usage.',
            'hero_text' => 'We plan screens, build core features, and prepare mobile products that feel clear, fast, and brand-aligned.',
            'work_images' => ['our_services_2.png', 'our_services.png', 'hero.png'],
            'process' => ['Scope', 'Prototype', 'Build', 'QA', 'Release'],
            'metrics' => [
                ['value' => '2X', 'label' => 'Faster Flow'],
                ['value' => 'iOS', 'label' => 'Ready'],
                ['value' => 'Android', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'App Prototype', 'price' => '$799', 'tag' => 'Validate', 'features' => ['Core screen designs', 'Clickable prototype', 'User flow map', 'Handoff files']],
                ['name' => 'MVP App', 'price' => '$1,899', 'tag' => 'Popular', 'features' => ['Core app build', 'Backend connection', 'Testing support', 'Store-ready assets']],
                ['name' => 'Full App Product', 'price' => '$3,499+', 'tag' => 'Scale', 'features' => ['Advanced features', 'Admin dashboard', 'API integrations', 'Maintenance plan']],
            ],
        ],
        'software' => [
            'label' => 'Business Software',
            'badge' => 'Business Systems',
            'icon' => 'ri-tools-line',
            'image' => 'hero.png',
            'hero_kicker' => 'Digital systems that streamline operations',
            'hero_title' => 'Custom systems that organize work and reduce manual effort.',
            'hero_text' => 'We build dashboards, records, workflows, reports, and team tools around the way your business actually operates.',
            'work_images' => ['hero.png', 'our_services.png', 'portfolio_section.png'],
            'process' => ['Audit', 'Flow Design', 'Development', 'Testing', 'Training'],
            'metrics' => [
                ['value' => '40%', 'label' => 'Less Manual Work'],
                ['value' => 'Live', 'label' => 'Reports'],
                ['value' => 'Role', 'label' => 'Access'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'System Starter', 'price' => '$999', 'tag' => 'Internal', 'features' => ['Core modules', 'User roles', 'Basic reports', 'Setup support']],
                ['name' => 'Business System', 'price' => '$2,499', 'tag' => 'Popular', 'features' => ['Multiple modules', 'Dashboard reports', 'Workflow automation', 'Data import']],
                ['name' => 'Enterprise Suite', 'price' => '$4,999+', 'tag' => 'Scale', 'features' => ['Custom ERP/CRM', 'Advanced permissions', 'Integrations', 'Training and support']],
            ],
        ],
        'cloud' => [
            'label' => 'Cloud & Infrastructure',
            'badge' => 'Infrastructure',
            'icon' => 'ri-cloud-line',
            'image' => 'hero.png',
            'hero_kicker' => 'Reliable, scalable, and secure technology foundations',
            'hero_title' => 'Backends, APIs, and cloud setups that keep products moving.',
            'hero_text' => 'We design secure server-side foundations, automate deployment, and keep the technical base easy to maintain.',
            'work_images' => ['hero.png', 'contact_us.png', 'our_services.png'],
            'process' => ['Architecture', 'Build', 'Secure', 'Deploy', 'Monitor'],
            'metrics' => [
                ['value' => '99%', 'label' => 'Uptime Goal'],
                ['value' => 'API', 'label' => 'Ready'],
                ['value' => 'SSL', 'label' => 'Secure'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Backend Starter', 'price' => '$499', 'tag' => 'Setup', 'features' => ['API setup', 'Database schema', 'Auth basics', 'Deployment notes']],
                ['name' => 'Cloud Launch', 'price' => '$1,299', 'tag' => 'Popular', 'features' => ['Cloud server setup', 'CI/CD pipeline', 'Security hardening', 'Monitoring setup']],
                ['name' => 'Scale Infrastructure', 'price' => '$2,499+', 'tag' => 'Scale', 'features' => ['Advanced architecture', 'Load-ready setup', 'Backups', 'Ongoing optimization']],
            ],
        ],
        'ai' => [
            'label' => 'AI & Intelligent Automation',
            'badge' => 'Modern Automation',
            'icon' => 'ri-robot-line',
            'image' => 'our_services_2.png',
            'hero_kicker' => 'Transform workflows with modern AI technologies',
            'hero_title' => 'Automation, AI integration, and intelligent SaaS tools for modern teams.',
            'hero_text' => 'We connect systems, automate repeat tasks, and build AI-driven assistants that optimize operations.',
            'work_images' => ['our_services_2.png', 'hero.png', 'portfolio_section.png'],
            'process' => ['Map', 'Prototype', 'Integrate', 'Automate', 'Improve'],
            'metrics' => [
                ['value' => '60%', 'label' => 'Time Saved'],
                ['value' => 'AI', 'label' => 'Ready'],
                ['value' => 'Live', 'label' => 'Dashboards'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Automation Starter', 'price' => '$699', 'tag' => 'Quick Win', 'features' => ['Workflow map', '1 automation flow', 'Tool connection', 'Basic testing']],
                ['name' => 'Smart Operations', 'price' => '$1,799', 'tag' => 'Popular', 'features' => ['Multiple workflows', 'Dashboard setup', 'API connections', 'Team handover']],
                ['name' => 'AI Product Innovation', 'price' => '$3,499+', 'tag' => 'Scale', 'features' => ['SaaS planning', 'AI Chatbot & RAG setup', 'Analytics layer', 'Ongoing iteration']],
            ],
        ],
        'marketing' => [
            'label' => 'Growth Marketing',
            'badge' => 'Growth Service',
            'icon' => 'ri-megaphone-line',
            'image' => 'contact_us.png',
            'hero_kicker' => 'Drive traffic, leads, and measurable business growth',
            'hero_title' => 'Campaign systems that attract, convert, and keep improving.',
            'hero_text' => 'We combine SEO, paid campaigns, social content, and email flows into practical growth activity your business can measure.',
            'work_images' => ['contact_us.png', 'portfolio_section.png', 'hero.png'],
            'process' => ['Research', 'Plan', 'Launch', 'Measure', 'Optimize'],
            'metrics' => [
                ['value' => '3X', 'label' => 'Reach Goal'],
                ['value' => 'SEO', 'label' => 'Ready'],
                ['value' => 'PPC', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Marketing Starter', 'price' => '$299', 'tag' => 'Launch', 'features' => ['Audit and plan', 'Keyword direction', 'Basic content plan', 'Monthly reporting']],
                ['name' => 'Growth Campaign', 'price' => '$799', 'tag' => 'Popular', 'features' => ['SEO and ads setup', 'Campaign creatives', 'Landing page guidance', 'Performance reports']],
                ['name' => 'Scale Marketing', 'price' => '$1,499+', 'tag' => 'Scale', 'features' => ['Multi-channel strategy', 'Content calendar', 'Conversion tracking', 'Optimization sprints']],
            ],
        ],
    ],

    'pages' => [
        // Category 1: Branding & Creative
        'logo-visual-identity' => [
            'category' => 'branding',
            'title' => 'Logo & Visual Identity',
            'headline' => 'Appealing Logo Designs & Visual Identity Systems Built For Leaders',
            'intro' => 'We create modern logo concepts, brand marks, typography rules, stationery previews, and full vector deliverables.',
            'image' => 'portfolio_section.png',
            'work_images' => ['portfolio_section.png', 'our_services_2.png', 'hero.png'],
            'package_label' => 'Logo & Visual Identity Packages',
            'features' => [
                ['icon' => 'ri-paint-brush-line', 'title' => 'Custom Logo Concepts', 'text' => 'Unique logo directions shaped around your brand vision, target audience, and industry standards.'],
                ['icon' => 'ri-palette-line', 'title' => 'Color & Typography System', 'text' => 'Harmonious color palettes and font pairings so your visual identity stays crisp everywhere.'],
                ['icon' => 'ri-folder-download-line', 'title' => 'Full Vector Deliverables', 'text' => 'SVG, EPS, PNG, and print-ready PDF files prepared for web, social media, and packaging.'],
            ],
            'work' => [
                ['label' => 'Logo', 'name' => 'Urban Cafe Brand', 'text' => 'Friendly logo direction for a modern cafe with strong recall.'],
                ['label' => 'Identity', 'name' => 'Realty Solutions Mark', 'text' => 'Clean property mark designed for trust and scalability.'],
                ['label' => 'Mockup', 'name' => 'AM Autos Brand Kit', 'text' => 'Complete logo system showcased across digital and physical touchpoints.'],
            ],
            'packages' => [
                ['name' => 'Starter Logo Package', 'price' => '$149', 'tag' => 'Launch', 'features' => ['2 logo concepts', '2 revision rounds', 'Primary logo files', 'PNG and JPG delivery']],
                ['name' => 'Growth Identity Package', 'price' => '$299', 'tag' => 'Most Popular', 'features' => ['4 logo concepts', '4 revision rounds', 'Color palette & typography', 'Business card mockup']],
                ['name' => 'Premium Brand System', 'price' => '$499', 'tag' => 'Full Kit', 'features' => ['6 logo concepts', 'Stationery design', 'Banner design set', 'Editable vector source files']],
            ],
        ],
        'brand-guidelines' => [
            'category' => 'branding',
            'title' => 'Brand Guidelines',
            'headline' => 'Comprehensive Brand Guidelines For Complete Visual Consistency',
            'intro' => 'We build complete brand style guides covering logo usage, color palettes, typography, iconography, and voice.',
            'image' => 'our_services_2.png',
            'features' => [
                ['icon' => 'ri-booklet-line', 'title' => 'Brand Rulebook', 'text' => 'Clear do’s and don’ts for logo placement, spacing, background contrast, and clear space.'],
                ['icon' => 'ri-contrast-drop-2-line', 'title' => 'Color & Font Specs', 'text' => 'HEX, RGB, CMYK color codes along with primary and secondary typography pairings.'],
                ['icon' => 'ri-team-line', 'title' => 'Team Handoff Guide', 'text' => 'Easy-to-follow guide so designers, marketers, and developers maintain visual consistency.'],
            ],
            'work' => [
                ['label' => 'Guidelines', 'name' => 'TechCorp Style Guide', 'text' => 'Detailed 30-page brand manual covering all digital and print rules.'],
                ['label' => 'Brand System', 'name' => 'Nova Traders Standards', 'text' => 'Visual standards manual for international trading firm.'],
                ['label' => 'Identity', 'name' => 'Fresh Supermarket Manual', 'text' => 'Brand guidelines covering storefront, uniform, and digital channels.'],
            ],
        ],
        'marketing-collateral' => [
            'category' => 'branding',
            'title' => 'Marketing Collateral',
            'headline' => 'High-Impact Marketing Collateral For Print & Digital Campaigns',
            'intro' => 'We design business cards, brochures, flyers, company profiles, letterheads, and presentation decks.',
            'features' => [
                ['icon' => 'ri-bank-card-line', 'title' => 'Stationery Suite', 'text' => 'Business cards, letterheads, envelopes, and email signatures crafted to impress.'],
                ['icon' => 'ri-file-text-line', 'title' => 'Brochures & Flyers', 'text' => 'Bi-fold, tri-fold, and promotional flyers optimized for print and PDF downloads.'],
                ['icon' => 'ri-slideshow-line', 'title' => 'Company Decks', 'text' => 'Polished pitch decks and corporate presentations that capture client interest.'],
            ],
            'work' => [
                ['label' => 'Stationery', 'name' => 'Executive Card & Letterhead', 'text' => 'Minimalist corporate print collateral with gold foil accents.'],
                ['label' => 'Brochure', 'name' => 'Real Estate Portfolio Book', 'text' => 'High-gloss property showcase booklet.'],
                ['label' => 'Presentation', 'name' => 'Investor Pitch Deck', 'text' => '20-slide investor pitch presentation for tech startup.'],
            ],
        ],
        'social-media-assets' => [
            'category' => 'branding',
            'title' => 'Social Media Assets',
            'headline' => 'Branded Social Media Kits For Consistent Daily Posting',
            'intro' => 'We design post templates, profile banners, story highlights, ad graphics, and promotional campaign visuals.',
            'features' => [
                ['icon' => 'ri-layout-grid-line', 'title' => 'Post Templates', 'text' => 'Editable Canva / Photoshop templates for offers, announcements, and quotes.'],
                ['icon' => 'ri-image-edit-line', 'title' => 'Cover & Profile Art', 'text' => 'Custom header banners for LinkedIn, Facebook, Twitter, YouTube, and Instagram.'],
                ['icon' => 'ri-megaphone-line', 'title' => 'Ad Creatives', 'text' => 'High-converting graphic banners tailored for Meta and Google Ad placements.'],
            ],
            'work' => [
                ['label' => 'Instagram', 'name' => 'E-Commerce Launch Grid', 'text' => '9-tile Instagram grid layout for new product release.'],
                ['label' => 'Facebook', 'name' => 'Service Promo Pack', 'text' => 'Cohesive cover photos, stories, and feed posts for local agency.'],
                ['label' => 'Templates', 'name' => 'Monthly Content Kit', 'text' => 'Reusable social post templates for easy internal management.'],
            ],
        ],
        'packaging-print-design' => [
            'category' => 'branding',
            'title' => 'Packaging & Print Design',
            'headline' => 'Shelf-Ready Packaging & Premium Print Design',
            'intro' => 'We create product packaging concepts, box dielines, bottle labels, pouches, and print-ready supplier files.',
            'features' => [
                ['icon' => 'ri-box-3-line', 'title' => 'Product Packaging', 'text' => 'Retail box design, mailer boxes, and pouch packaging that grab customer attention.'],
                ['icon' => 'ri-price-tag-3-line', 'title' => 'Labels & Sleeves', 'text' => 'Custom bottle labels, jar stickers, and product sleeves with clear typography.'],
                ['icon' => 'ri-printer-line', 'title' => 'Supplier Ready Dielines', 'text' => 'Exact bleed, margin, CMYK color spaces, and vector dieline files for commercial printing.'],
            ],
            'work' => [
                ['label' => 'Box', 'name' => 'Cosmetics Product Box', 'text' => 'Luxury foil-stamped box design for organic skincare.'],
                ['label' => 'Label', 'name' => 'Artisanal Beverage Label', 'text' => 'Custom die-cut bottle label with barcode and nutrition details.'],
                ['label' => 'Package', 'name' => 'Subscription Mailer Box', 'text' => 'Unboxing experience design for e-commerce brand.'],
            ],
        ],

        // Category 2: Web Solutions
        'corporate-websites' => [
            'category' => 'web',
            'title' => 'Corporate Websites',
            'headline' => 'High-Performance Corporate Websites That Build Trust & Capture Leads',
            'intro' => 'We design and develop corporate websites, company profiles, service portals, and lead generation platforms.',
            'image' => 'our_services.png',
            'features' => [
                ['icon' => 'ri-pages-line', 'title' => 'Service & About Pages', 'text' => 'Structured layouts that clearly communicate your company values, services, and team.'],
                ['icon' => 'ri-smartphone-line', 'title' => '100% Mobile Responsive', 'text' => 'Fluid design that adapts seamlessly to desktop, tablet, and smartphone screens.'],
                ['icon' => 'ri-search-eye-line', 'title' => 'Built-In Technical SEO', 'text' => 'Clean HTML5 semantics, schema markup, and metadata optimization for high search rankings.'],
            ],
            'work' => [
                ['label' => 'Corporate', 'name' => 'Global Logistics Platform', 'text' => 'Enterprise corporate site with service calculator and tracking.'],
                ['label' => 'Consulting', 'name' => 'Financial Advisory Website', 'text' => 'High-trust corporate portal with consultation booking.'],
                ['label' => 'B2B', 'name' => 'Manufacturing Solutions Hub', 'text' => 'Industrial product catalog and RFP inquiry form.'],
            ],
        ],
        'ecommerce-stores' => [
            'category' => 'web',
            'title' => 'E-Commerce Stores',
            'headline' => 'Scalable Online Stores Designed To Maximize Sales & Conversion Rate',
            'intro' => 'We build fast, secure e-commerce platforms with product filtering, shopping carts, checkout, and payment gateways.',
            'features' => [
                ['icon' => 'ri-shopping-cart-line', 'title' => 'Product Management', 'text' => 'Category trees, inventory tracking, variant selections, and customer reviews.'],
                ['icon' => 'ri-bank-card-line', 'title' => 'Seamless Checkout', 'text' => 'One-page checkout connected with Stripe, PayPal, and local payment methods.'],
                ['icon' => 'ri-dashboard-3-line', 'title' => 'Admin Order Dashboard', 'text' => 'Easy-to-use admin panel for tracking orders, customers, coupons, and sales reports.'],
            ],
            'work' => [
                ['label' => 'Store', 'name' => 'Urban Fashion Boutique', 'text' => 'High-speed apparel online store with instant filter and multi-currency.'],
                ['label' => 'Electronics', 'name' => 'TechGadgets Store', 'text' => '10,000+ SKU store with live stock updates and fast search.'],
                ['label' => 'B2C', 'name' => 'Organic Foods Market', 'text' => 'Subscription-based e-commerce store with recurring deliveries.'],
            ],
        ],
        'custom-web-applications' => [
            'category' => 'web',
            'title' => 'Custom Web Applications',
            'headline' => 'Tailored Web Applications Built For Complex Workflows & Portals',
            'intro' => 'We build custom web apps, customer portals, internal management tools, and web-based SaaS platforms.',
            'features' => [
                ['icon' => 'ri-dashboard-line', 'title' => 'Interactive Dashboards', 'text' => 'Real-time metrics, interactive charts, data tables, and custom export tools.'],
                ['icon' => 'ri-user-settings-line', 'title' => 'Role-Based Access Control', 'text' => 'Multi-tier permissions for admins, managers, clients, and staff members.'],
                ['icon' => 'ri-database-2-line', 'title' => 'Custom Database & Logic', 'text' => 'Scalable backend database structure built with Laravel, Node, or Python.'],
            ],
            'work' => [
                ['label' => 'Portal', 'name' => 'Client Project Hub', 'text' => 'Secure portal for sharing project files, milestone signoffs, and invoices.'],
                ['label' => 'App', 'name' => 'Property Listing Management', 'text' => 'Web application for real estate agents to manage leads and listings.'],
                ['label' => 'SaaS', 'name' => 'Invoice Generator Tool', 'text' => 'Browser-based software application with automated PDF export.'],
            ],
        ],
        'cms-development-services' => [
            'category' => 'web',
            'title' => 'CMS Development',
            'headline' => 'CMS Websites Your Team Can Update Without Developer Assistance',
            'intro' => 'We build custom WordPress, Elementor, and custom CMS websites that empower non-technical staff to edit content easily.',
            'features' => [
                ['icon' => 'ri-edit-box-line', 'title' => 'Visual Page Builder', 'text' => 'Custom block libraries and drag-and-drop page editing tools.'],
                ['icon' => 'ri-folder-settings-line', 'title' => 'Content Management', 'text' => 'Effortlessly create and manage blogs, services, portfolio items, and staff bios.'],
                ['icon' => 'ri-shield-check-line', 'title' => 'Security & Speed Hardening', 'text' => 'Caching, firewall setup, automatic database backups, and security monitoring.'],
            ],
            'work' => [
                ['label' => 'WordPress', 'name' => 'News & Publishing Hub', 'text' => 'High-traffic content website with custom category layouts.'],
                ['label' => 'Custom CMS', 'name' => 'Healthcare Clinic Network', 'text' => 'Multi-location CMS site with doctor schedules and location editor.'],
                ['label' => 'Corporate', 'name' => 'Law Firm Portal', 'text' => 'Clean CMS website with attorney profiles and case study library.'],
            ],
        ],
        'website-revamps-optimization' => [
            'category' => 'web',
            'title' => 'Website Revamps & Optimization',
            'headline' => 'Modernize Your Website For Lightning Speed & Higher Conversions',
            'intro' => 'We audit, redesign, and optimize existing websites to improve loading speeds, UI UX, and lead conversion rates.',
            'features' => [
                ['icon' => 'ri-refresh-line', 'title' => 'Modern UI/UX Overhaul', 'text' => 'Transform outdated layouts into stunning, high-converting visual designs.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Core Web Vitals Optimization', 'text' => 'Sub-second page load speeds with image compression, code minification, and CDN.'],
                ['icon' => 'ri-route-line', 'title' => 'Conversion Rate Optimization', 'text' => 'Strategic CTA placement, simplified contact forms, and better user journeys.'],
            ],
            'work' => [
                ['label' => 'Redesign', 'name' => 'SaaS Landing Page Revamp', 'text' => '300% increase in signups after UI modernization.'],
                ['label' => 'Speed', 'name' => 'E-Commerce Speed Cleanup', 'text' => 'Page load time reduced from 6.8s to 1.1s.'],
                ['label' => 'Revamp', 'name' => 'Dental Practice Website', 'text' => 'Complete visual redesign with online appointment booking.'],
            ],
        ],

        // Category 3: Mobile Applications
        'android-development' => [
            'category' => 'app',
            'title' => 'Android Development',
            'headline' => 'Native & High-Performance Android Apps Built For Google Play',
            'intro' => 'We design and develop Android apps using Kotlin and Java with responsive screens, offline sync, and API backends.',
            'features' => [
                ['icon' => 'ri-android-line', 'title' => 'Modern Kotlin Architecture', 'text' => 'Clean Code MVVM architecture built for speed, stability, and scale.'],
                ['icon' => 'ri-notification-3-line', 'title' => 'Push Notifications & GPS', 'text' => 'Integrated Firebase messaging, location services, background workers, and camera APIs.'],
                ['icon' => 'ri-upload-cloud-line', 'title' => 'Google Play Publishing', 'text' => 'Complete Store Listing optimization, APK/AAB bundle building, and Play Console approval.'],
            ],
            'work' => [
                ['label' => 'Android', 'name' => 'On-Demand Delivery App', 'text' => 'Real-time driver tracking and customer order notifications.'],
                ['label' => 'Fitness', 'name' => 'Workout Tracker App', 'text' => 'Offline activity logging with step count and Bluetooth sync.'],
                ['label' => 'Utility', 'name' => 'Smart Home Remote App', 'text' => 'IoT controller app with instant device pairing.'],
            ],
        ],
        'ios-development' => [
            'category' => 'app',
            'title' => 'iOS Development',
            'headline' => 'Premium iOS Applications Crafted For iPhone, iPad, & Apple Ecosystem',
            'intro' => 'We build native iOS applications using Swift and SwiftUI following Apple’s strict Human Interface Guidelines.',
            'features' => [
                ['icon' => 'ri-apple-line', 'title' => 'Swift & SwiftUI UI', 'text' => 'Sleek, fluid interfaces built specifically for iOS devices.'],
                ['icon' => 'ri-shield-user-line', 'title' => 'Biometric Security & Pay', 'text' => 'Apple Pay, Face ID / Touch ID authentication, and Secure Enclave data protection.'],
                ['icon' => 'ri-store-2-line', 'title' => 'App Store Compliance', 'text' => 'Flawless submission prep, TestFlight beta management, and App Store approval.'],
            ],
            'work' => [
                ['label' => 'iOS', 'name' => 'Luxury Hotel Concierge App', 'text' => 'Room booking, keyless entry, and spa reservation flow.'],
                ['label' => 'Finance', 'name' => 'Mobile Banking Wallet', 'text' => 'Biometric login and instant peer-to-peer money transfers.'],
                ['label' => 'Lifestyle', 'name' => 'Meditation & Mindfulness App', 'text' => 'Audio streaming with Apple Health Kit integration.'],
            ],
        ],
        'cross-platform-apps-dev' => [
            'category' => 'app',
            'title' => 'Cross-Platform Apps',
            'headline' => 'Multi-Platform Mobile Apps Built Fast With Flutter & React Native',
            'intro' => 'We develop cross-platform mobile apps for iOS and Android simultaneously, reducing development cost and launch timeline.',
            'features' => [
                ['icon' => 'ri-stack-line', 'title' => 'Single Shared Codebase', 'text' => 'Deploy to both App Store and Google Play from one unified code foundation.'],
                ['icon' => 'ri-smartphone-line', 'title' => '60FPS Native UI', 'text' => 'Smooth 60 FPS animations and UI widgets that feel native on both platforms.'],
                ['icon' => 'ri-links-line', 'title' => 'Full Hardware Integration', 'text' => 'Camera, GPS, Bluetooth, Push Notifications, and SQLite local storage support.'],
            ],
            'work' => [
                ['label' => 'Flutter', 'name' => 'Ride Hailing App', 'text' => 'Cross-platform passenger and driver app launched in 60 days.'],
                ['label' => 'React Native', 'name' => 'Social Marketplace', 'text' => 'Peer-to-peer buying and selling app with in-app chat.'],
                ['label' => 'Business', 'name' => 'Sales Representative Tool', 'text' => 'Field agent ordering app with offline inventory data.'],
            ],
        ],
        'mobile-ui-ux-design' => [
            'category' => 'app',
            'title' => 'UI/UX Design',
            'headline' => 'Intuitive Mobile UI/UX Design Engineered For High User Engagement',
            'intro' => 'We design mobile app wireframes, user journeys, interactive prototypes, and design systems for mobile applications.',
            'features' => [
                ['icon' => 'ri-drag-move-line', 'title' => 'User Journey Mapping', 'text' => 'Streamlined onboarding, navigation, and checkout flows that minimize dropoff.'],
                ['icon' => 'ri-pencil-ruler-2-line', 'title' => 'Figma Design System', 'text' => 'Component libraries, typography scales, dark/light themes, and screen kits.'],
                ['icon' => 'ri-play-circle-line', 'title' => 'Clickable Prototypes', 'text' => 'Interactive screen previews to test user flows before starting development.'],
            ],
            'work' => [
                ['label' => 'Figma', 'name' => 'Food Delivery App Wireframe', 'text' => 'Complete 40-screen mobile user experience design.'],
                ['label' => 'UX Audit', 'name' => 'Fintech App Checkout Flow', 'text' => 'Redesigned transfer screens increasing completion rate by 45%.'],
                ['label' => 'System', 'name' => 'Mobile Design Tokens', 'text' => 'Reusable mobile UI kit for multi-product startup.'],
            ],
        ],
        'app-support-maintenance' => [
            'category' => 'app',
            'title' => 'App Support & Maintenance',
            'headline' => 'Ongoing Mobile App Maintenance, Monitoring, & Feature Upgrades',
            'intro' => 'We maintain, update, and optimize live iOS and Android apps to ensure maximum uptime, security, and OS compatibility.',
            'features' => [
                ['icon' => 'ri-bug-line', 'title' => 'Crash Monitoring & Fixes', 'text' => 'Proactive Crashlytics error monitoring and emergency patch releases.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'OS Version Compatibility', 'text' => 'Annual updates for latest iOS and Android OS releases and API guidelines.'],
                ['icon' => 'ri-refresh-line', 'title' => 'Feature Expansion Sprints', 'text' => 'Regular feature updates, UI polish, and performance optimizations.'],
            ],
            'work' => [
                ['label' => 'Care', 'name' => 'SaaS Mobile App Maintenance', 'text' => '24/7 server and app uptime monitoring with 99.9% uptime.'],
                ['label' => 'Update', 'name' => 'iOS 18 & Android 15 Migration', 'text' => 'Updated SDKs and privacy permissions for 100k user app.'],
                ['label' => 'Audit', 'name' => 'Memory Leak Optimization', 'text' => 'Reduced app crash rate to under 0.01%.'],
            ],
        ],

        // Category 4: Business Software
        'erp-solutions' => [
            'category' => 'software',
            'title' => 'ERP Solutions',
            'headline' => 'Custom ERP Systems Connecting Operations, Inventory, & Finance',
            'intro' => 'We build enterprise ERP platforms that unify supply chain, HR, finance, sales, and manufacturing into one database.',
            'features' => [
                ['icon' => 'ri-building-4-line', 'title' => 'Multi-Module Systems', 'text' => 'Connect sales orders, procurement, inventory, accounting, and staff.'],
                ['icon' => 'ri-bar-chart-box-line', 'title' => 'Real-Time Reports', 'text' => 'Live executive dashboards, P&L reports, and operational metrics.'],
                ['icon' => 'ri-lock-password-line', 'title' => 'Enterprise Security', 'text' => 'Role-based access, SSL encryption, audit logs, and automated daily backups.'],
            ],
            'work' => [
                ['label' => 'ERP', 'name' => 'Factory Operations ERP', 'text' => 'Production scheduling, material tracking, and staff management.'],
                ['label' => 'Retail', 'name' => 'Multi-Branch Retail System', 'text' => 'Central inventory and point-of-sale ERP across 15 stores.'],
                ['label' => 'Logistics', 'name' => 'Fleet & Dispatch ERP', 'text' => 'Vehicle tracking, maintenance logs, and driver dispatching.'],
            ],
        ],
        'crm-platforms' => [
            'category' => 'software',
            'title' => 'CRM Platforms',
            'headline' => 'Intelligent CRM Platforms To Manage Leads, Deals, & Relationships',
            'intro' => 'We build custom CRM systems that help sales teams capture leads, track deal pipelines, and automate follow-ups.',
            'features' => [
                ['icon' => 'ri-contacts-book-line', 'title' => 'Visual Deal Pipelines', 'text' => 'Drag-and-drop lead stages, deal values, probabilities, and contact history.'],
                ['icon' => 'ri-calendar-check-line', 'title' => 'Automated Reminders', 'text' => 'Automated follow-up tasks, call logs, email notifications, and WhatsApp alerts.'],
                ['icon' => 'ri-line-chart-line', 'title' => 'Sales Analytics', 'text' => 'Rep performance tracking, revenue forecasting, and lead source ROI reports.'],
            ],
            'work' => [
                ['label' => 'CRM', 'name' => 'Real Estate Sales CRM', 'text' => 'Buyer management, property matching, and automated SMS alerts.'],
                ['label' => 'B2B', 'name' => 'Corporate Sales Pipeline', 'text' => 'Multi-stage proposal and deal tracking system.'],
                ['label' => 'Agency', 'name' => 'Client Project CRM', 'text' => 'Contract management, client communication history, and invoicing.'],
            ],
        ],
        'hr-inventory-management' => [
            'category' => 'software',
            'title' => 'HR & Inventory Management',
            'headline' => 'Integrated HR & Inventory Systems For Workforce & Stock Control',
            'intro' => 'We create software solutions for managing employee records, attendance, payroll, warehouse stock, and asset tracking.',
            'features' => [
                ['icon' => 'ri-archive-stack-line', 'title' => 'Warehouse Stock Control', 'text' => 'Real-time inventory levels, barcode scanning, stock transfers, and low-stock alerts.'],
                ['icon' => 'ri-team-line', 'title' => 'Employee & Payroll Hub', 'text' => 'Attendance tracking, leave requests, salary slips, and performance evaluations.'],
                ['icon' => 'ri-file-chart-line', 'title' => 'Automated Audit Reports', 'text' => 'Comprehensive inventory valuation and workforce attendance reporting.'],
            ],
            'work' => [
                ['label' => 'Inventory', 'name' => 'Pharmaceutical Warehouse App', 'text' => 'Batch number tracking, expiry alerts, and stock movements.'],
                ['label' => 'HRM', 'name' => 'Corporate Attendance Portal', 'text' => 'Biometric check-in sync, leave approvals, and automated payroll.'],
                ['label' => 'System', 'name' => 'Equipment & Asset Manager', 'text' => 'Company asset tracking and maintenance scheduling.'],
            ],
        ],
        'billing-accounting-systems' => [
            'category' => 'software',
            'title' => 'Billing & Accounting Systems',
            'headline' => 'Automated Billing & Invoicing Systems For Financial Clarity',
            'intro' => 'We build custom billing software for generating estimates, tax invoices, receipts, recurring subscriptions, and ledger reports.',
            'features' => [
                ['icon' => 'ri-bill-line', 'title' => 'Instant Invoice Generation', 'text' => 'Create PDF quotes, tax invoices, and receipts in seconds with custom branding.'],
                ['icon' => 'ri-money-dollar-circle-line', 'title' => 'Payment & Overdue Tracking', 'text' => 'Track paid, partial, and pending payments with automated payment reminder emails.'],
                ['icon' => 'ri-file-list-3-line', 'title' => 'Tax & Ledger Reports', 'text' => 'Income/expense tracking, tax summaries, customer account statements, and exports.'],
            ],
            'work' => [
                ['label' => 'Billing', 'name' => 'ISP Recurring Invoicing Tool', 'text' => 'Automated monthly subscriber billing and SMS notifications.'],
                ['label' => 'POS', 'name' => 'Retail Billing & Tax POS', 'text' => 'Thermal printer POS software with tax breakdown.'],
                ['label' => 'Finance', 'name' => 'Vendor Accounting Portal', 'text' => 'Accounts payable and receivable management tool.'],
            ],
        ],
        'industry-specific-software' => [
            'category' => 'software',
            'title' => 'Industry-Specific Software',
            'headline' => 'Custom Systems Built For Schools, Hospitals, Real Estate, & Retail',
            'intro' => 'We develop tailored management systems designed specifically for the unique workflows of your industry.',
            'features' => [
                ['icon' => 'ri-hospital-line', 'title' => 'Healthcare & Clinic Systems', 'text' => 'Patient EMR records, appointment scheduling, doctor shifts, and pharmacy billing.'],
                ['icon' => 'ri-book-read-line', 'title' => 'School & Academy Portals', 'text' => 'Student admissions, fee collection, gradebooks, exams, and parent portals.'],
                ['icon' => 'ri-shield-check-line', 'title' => 'Compliance & Data Safety', 'text' => 'Built to meet industry regulations, data privacy laws, and role-based security.'],
            ],
            'work' => [
                ['label' => 'Hospital', 'name' => 'Medical Center Management', 'text' => 'EMR, OPD appointment queue, and laboratory test reporting.'],
                ['label' => 'School', 'name' => 'Campus Information System', 'text' => '1,500 student portal with online fee payment gateway.'],
                ['label' => 'Real Estate', 'name' => 'Property Lease Manager', 'text' => 'Tenant rent collection, contract renewals, and maintenance tickets.'],
            ],
        ],

        // Category 5: Cloud & Infrastructure
        'rest-api-development' => [
            'category' => 'cloud',
            'title' => 'REST API Development',
            'headline' => 'Secure, Scalable RESTful APIs Built For App & Web Integration',
            'intro' => 'We design and build fast REST APIs connecting web frontends, mobile apps, third-party software, and payment portals.',
            'features' => [
                ['icon' => 'ri-plug-line', 'title' => 'Clean Endpoint Architecture', 'text' => 'RESTful endpoints with JSON payloads, rate limiting, and versioning.'],
                ['icon' => 'ri-lock-line', 'title' => 'JWT & OAuth2 Security', 'text' => 'Token authentication, API key validation, and encrypted data transfers.'],
                ['icon' => 'ri-file-code-line', 'title' => 'Interactive API Docs', 'text' => 'Swagger / Postman documentation for fast frontend and partner integration.'],
            ],
            'work' => [
                ['label' => 'API', 'name' => 'Mobile App Backend API', 'text' => 'High-throughput API serving 50,000 daily active app users.'],
                ['label' => 'Fintech', 'name' => 'Payment Gateway Wrapper API', 'text' => 'Unified API connecting 3 payment processors.'],
                ['label' => 'SaaS', 'name' => 'Public Developer API', 'text' => 'Rate-limited REST API for external developer ecosystem.'],
            ],
        ],
        'cloud-deployment-services' => [
            'category' => 'cloud',
            'title' => 'Cloud Deployment',
            'headline' => 'Enterprise Cloud Setup On AWS, Google Cloud, DigitalOcean, & Azure',
            'intro' => 'We deploy, configure, and manage cloud servers, load balancers, SSL certificates, and database clusters.',
            'features' => [
                ['icon' => 'ri-server-line', 'title' => 'Cloud Infrastructure Setup', 'text' => 'Provision EC2/Compute instances, Docker containers, and Nginx/Apache web servers.'],
                ['icon' => 'ri-shield-keyhole-line', 'title' => 'SSL, Firewall & Security', 'text' => 'Domain DNS configuration, Let’s Encrypt SSL, UFW/Cloud firewalls, and DDoS shielding.'],
                ['icon' => 'ri-loop-left-line', 'title' => 'Automated Disaster Backups', 'text' => 'Daily automated database snapshots and offsite S3 file backups.'],
            ],
            'work' => [
                ['label' => 'AWS', 'name' => 'High-Availability Web Server', 'text' => 'AWS EC2 + RDS setup with auto-scaling and CloudFront CDN.'],
                ['label' => 'Migration', 'name' => 'Legacy Server to Cloud Move', 'text' => 'Zero-downtime database and file migration to DigitalOcean.'],
                ['label' => 'Security', 'name' => 'Server Hardening Sprint', 'text' => 'Configured fail2ban, firewall rules, and SSH key authentication.'],
            ],
        ],
        'database-architecture' => [
            'category' => 'cloud',
            'title' => 'Database Architecture',
            'headline' => 'Optimized Relational & NoSQL Database Design For High Performance',
            'intro' => 'We design MySQL, PostgreSQL, MongoDB, and Redis database schemas built for speed, integrity, and scale.',
            'features' => [
                ['icon' => 'ri-database-2-line', 'title' => 'Normalized Schema Design', 'text' => 'Structured tables, foreign keys, indexes, and constraints built for clean query performance.'],
                ['icon' => 'ri-search-line', 'title' => 'Query Optimization', 'text' => 'Identify slow queries, add missing indexes, and optimize complex joins.'],
                ['icon' => 'ri-safe-2-line', 'title' => 'Replication & Failover', 'text' => 'Master-slave replication, Redis caching layer, and data integrity checks.'],
            ],
            'work' => [
                ['label' => 'PostgreSQL', 'name' => 'Financial Ledger Schema', 'text' => 'ACID-compliant database design for transaction handling.'],
                ['label' => 'Optimization', 'name' => 'Query Tuning Sprint', 'text' => 'Reduced slow query times from 4.2 seconds to 45 milliseconds.'],
                ['label' => 'Redis', 'name' => 'High-Speed Caching Layer', 'text' => 'Implemented Redis caching reducing database load by 70%.'],
            ],
        ],
        'server-management' => [
            'category' => 'cloud',
            'title' => 'Server Management',
            'headline' => '24/7 Managed Server Administration, Security, & Health Monitoring',
            'intro' => 'We manage Linux servers (Ubuntu, CentOS, Debian) ensuring high uptime, security patches, and performance tuning.',
            'features' => [
                ['icon' => 'ri-terminal-box-line', 'title' => 'System Administration', 'text' => 'Package updates, PHP/Node version upgrades, Cron job management, and SSL renewal.'],
                ['icon' => 'ri-radar-line', 'title' => '24/7 Uptime Monitoring', 'text' => 'Real-time CPU, RAM, disk space, and HTTP uptime monitoring with SMS alerts.'],
                ['icon' => 'ri-shield-cross-line', 'title' => 'Malware & Vulnerability Audit', 'text' => 'Server security audits, rootkit scanning, and vulnerability patching.'],
            ],
            'work' => [
                ['label' => 'Linux', 'name' => 'Dedicated Server Care', 'text' => 'Managed 4-node dedicated server setup for media publishing firm.'],
                ['label' => 'Monitoring', 'name' => 'Real-Time Alert Setup', 'text' => 'Automated server metric alerts via Telegram and Email.'],
                ['label' => 'Security', 'name' => 'Malware Removal & Hardening', 'text' => 'Cleaned compromised server and implemented strict file permissions.'],
            ],
        ],
        'devops-cicd' => [
            'category' => 'cloud',
            'title' => 'DevOps & CI/CD',
            'headline' => 'Automated Deployment Pipelines & DevOps For Rapid Code Release',
            'intro' => 'We set up GitHub Actions, GitLab CI, Docker containers, and continuous deployment workflows for software products.',
            'features' => [
                ['icon' => 'ri-git-branch-line', 'title' => 'Automated Deployment Pipelines', 'text' => 'Push code to main branch to trigger automatic testing, building, and production deployment.'],
                ['icon' => 'ri-inbox-archive-line', 'title' => 'Docker & Containerization', 'text' => 'Package applications into lightweight Docker containers for identical dev and prod environments.'],
                ['icon' => 'ri-settings-5-line', 'title' => 'Zero-Downtime Releases', 'text' => 'Deploy new features seamlessly without interrupting live users.'],
            ],
            'work' => [
                ['label' => 'CI/CD', 'name' => 'GitHub Actions Pipeline', 'text' => 'Automated testing and deployment setup for Laravel & React app.'],
                ['label' => 'Docker', 'name' => 'Microservices Containerization', 'text' => 'Dockerized Node.js services with docker-compose setup.'],
                ['label' => 'DevOps', 'name' => 'Staging & Prod Environment Sync', 'text' => 'Isolated staging environment with automated database seeding.'],
            ],
        ],

        // Category 6: AI & Intelligent Automation
        'ai-chatbots' => [
            'category' => 'ai',
            'title' => 'AI Chatbots',
            'headline' => 'Intelligent Conversational AI Chatbots For 24/7 Support & Sales',
            'intro' => 'We build custom AI chatbots powered by OpenAI ChatGPT and Gemini trained on your business documents and FAQs.',
            'features' => [
                ['icon' => 'ri-robot-2-line', 'title' => 'Custom Knowledge Base (RAG)', 'text' => 'Train the AI bot on your website content, PDFs, policy docs, and product specs.'],
                ['icon' => 'ri-question-answer-line', 'title' => 'Multi-Channel Integration', 'text' => 'Embed chatbot widget on your website, WhatsApp Business, Facebook Messenger, or Telegram.'],
                ['icon' => 'ri-customer-service-2-line', 'title' => 'Lead Qualification & Handoff', 'text' => 'Bot captures visitor details, answers questions, and routes hot leads to human team.'],
            ],
            'work' => [
                ['label' => 'AI Bot', 'name' => 'E-Commerce Order Assistant', 'text' => 'WhatsApp bot providing live order tracking and product support.'],
                ['label' => 'Support', 'name' => 'SaaS Helpdesk AI Bot', 'text' => 'Reduced support ticket volume by 65% with instant answer bot.'],
                ['label' => 'Leads', 'name' => 'Real Estate Qualification Bot', 'text' => 'Website chatbot qualifying buyer budget and location preferences.'],
            ],
        ],
        'business-process-automation' => [
            'category' => 'ai',
            'title' => 'Business Process Automation',
            'headline' => 'Automate Repetitive Workflows & Eliminate Manual Data Entry',
            'intro' => 'We connect forms, spreadsheets, CRMs, email tools, WhatsApp, and database systems using Zapier, Make, and custom scripts.',
            'features' => [
                ['icon' => 'ri-loop-right-line', 'title' => 'Trigger-Based Workflows', 'text' => 'Automatically route new form leads to sales reps, update CRMs, and send instant notifications.'],
                ['icon' => 'ri-whatsapp-line', 'title' => 'WhatsApp & SMS Automations', 'text' => 'Send instant payment receipts, appointment confirmations, and follow-up messages automatically.'],
                ['icon' => 'ri-links-line', 'title' => 'Tool & App Connections', 'text' => 'Integrate Google Sheets, Airtable, HubSpot, Stripe, Slack, and internal software.'],
            ],
            'work' => [
                ['label' => 'Leads', 'name' => 'Instant Lead Routing Flow', 'text' => 'Website form lead instantly sent to sales rep WhatsApp and CRM.'],
                ['label' => 'Admin', 'name' => 'Automated Invoice Reminders', 'text' => 'System automatically emails and texts overdue payment reminders.'],
                ['label' => 'Sync', 'name' => 'Form-to-Spreadsheet Sync', 'text' => 'Multi-channel survey responses consolidated into master spreadsheet.'],
            ],
        ],
        'saas-development' => [
            'category' => 'ai',
            'title' => 'SaaS Development',
            'headline' => 'Turn Your Idea Into A Scalable Multi-Tenant SaaS Platform',
            'intro' => 'We plan, design, and build software-as-a-service platforms complete with subscriptions, user roles, and dashboards.',
            'features' => [
                ['icon' => 'ri-rocket-line', 'title' => 'MVP Roadmap & Build', 'text' => 'Prioritize core features, launch fast, and start onboarding paying users.'],
                ['icon' => 'ri-user-star-line', 'title' => 'Multi-Tenant Architecture', 'text' => 'Isolated client data, team workspaces, custom domains, and user permission roles.'],
                ['icon' => 'ri-bank-card-line', 'title' => 'Stripe Billing & Plans', 'text' => 'Tiered subscription plans, free trials, coupon codes, and automated monthly billing.'],
            ],
            'work' => [
                ['label' => 'SaaS', 'name' => 'Social Media Scheduler MVP', 'text' => 'Multi-user SaaS platform built and launched in 90 days.'],
                ['label' => 'B2B', 'name' => 'HR Compliance SaaS', 'text' => 'Enterprise SaaS platform serving 40+ corporate clients.'],
                ['label' => 'Tool', 'name' => 'AI Content Generator SaaS', 'text' => 'Subscription tool with Stripe payments and API integration.'],
            ],
        ],
        'ai-integrations' => [
            'category' => 'ai',
            'title' => 'AI Integrations',
            'headline' => 'Integrate Gemini, OpenAI, & Claude APIs Into Your Applications',
            'intro' => 'We add AI intelligence to your existing web and mobile applications for text generation, document analysis, and data extraction.',
            'features' => [
                ['icon' => 'ri-plug-2-line', 'title' => 'LLM API Integration', 'text' => 'Connect GPT-4, Gemini Pro, and Claude models securely to your software.'],
                ['icon' => 'ri-file-text-line', 'title' => 'Document & OCR Parsing', 'text' => 'Automatically extract data from PDFs, receipts, invoices, and uploaded images.'],
                ['icon' => 'ri-search-code-line', 'title' => 'Smart Search & Categorization', 'text' => 'Implement vector semantic search and auto-tagging for large datasets.'],
            ],
            'work' => [
                ['label' => 'AI', 'name' => 'Invoice OCR Data Extractor', 'text' => 'AI tool parsing PDF invoices into structured accounting data.'],
                ['label' => 'Content', 'name' => 'Automated Product Writer', 'text' => 'E-commerce tool generating product descriptions from image uploads.'],
                ['label' => 'Analytics', 'name' => 'Customer Feedback Sentiment AI', 'text' => 'Real-time AI sentiment analysis on customer reviews.'],
            ],
        ],
        'analytics-business-intelligence' => [
            'category' => 'ai',
            'title' => 'Analytics & Business Intelligence',
            'headline' => 'Real-Time BI Dashboards Turning Scattered Data Into Actionable Insights',
            'intro' => 'We build custom BI analytics dashboards aggregating sales, marketing, financial, and operational data.',
            'features' => [
                ['icon' => 'ri-bar-chart-2-line', 'title' => 'Custom Executive KPI Boards', 'text' => 'Track revenue, customer acquisition cost, churn, ad spend ROI, and daily growth.'],
                ['icon' => 'ri-filter-3-line', 'title' => 'Interactive Filters & Drills', 'text' => 'Filter data by date range, team member, geographic region, or product category.'],
                ['icon' => 'ri-pie-chart-line', 'title' => 'Automated Weekly Email Reports', 'text' => 'Scheduled PDF dashboard summaries sent to management automatically.'],
            ],
            'work' => [
                ['label' => 'BI', 'name' => 'Executive Revenue Dashboard', 'text' => 'Unified data board aggregating Stripe, Google Ads, and CRM data.'],
                ['label' => 'Sales', 'name' => 'Multi-Branch Sales Tracker', 'text' => 'Real-time sales leaderboards across 10 retail locations.'],
                ['label' => 'Marketing', 'name' => 'Attribution Analytics Board', 'text' => 'Track campaign ROAS across Google, Facebook, and Organic channels.'],
            ],
        ],

        // Category 7: Growth Marketing
        'search-engine-optimization' => [
            'category' => 'marketing',
            'title' => 'Search Engine Optimization',
            'headline' => 'Rank #1 On Google & Capture Consistent Organic Customer Traffic',
            'intro' => 'We execute complete SEO strategies covering keyword research, technical cleanup, on-page optimization, and authority link building.',
            'features' => [
                ['icon' => 'ri-search-line', 'title' => 'High-Intent Keyword Strategy', 'text' => 'Target keywords your prospective customers search when ready to purchase.'],
                ['icon' => 'ri-file-search-line', 'title' => 'On-Page & Content Tuning', 'text' => 'Optimize titles, meta tags, headings, internal links, and content hierarchy.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Technical SEO & Speed Fixes', 'text' => 'Fix broken links, improve mobile usability, fix indexing errors, and boost speed.'],
            ],
            'work' => [
                ['label' => 'SEO', 'name' => 'Local Service Business SEO', 'text' => 'Ranked #1 for 15 target local keywords in 90 days.'],
                ['label' => 'E-Commerce', 'name' => 'Organic Store Traffic Push', 'text' => 'Increased organic monthly search traffic from 2k to 28k visitors.'],
                ['label' => 'B2B', 'name' => 'Corporate Blog Keyword Strategy', 'text' => 'Generated 250+ monthly inbound organic sales leads.'],
            ],
        ],
        'paid-advertising-google-meta' => [
            'category' => 'marketing',
            'title' => 'Paid Advertising (Google & Meta)',
            'headline' => 'High-ROI Google Search Ads, Meta Ads, & Retargeting Campaigns',
            'intro' => 'We create, manage, and scale paid search and social campaigns engineered to generate sales leads and customer purchases.',
            'features' => [
                ['icon' => 'ri-advertisement-line', 'title' => 'Google Search & Shopping Ads', 'text' => 'Target active search buyers with laser-focused ad groups, keywords, and extensions.'],
                ['icon' => 'ri-focus-3-line', 'title' => 'Meta (FB & IG) Video & Carousel Ads', 'text' => 'Scroll-stopping visual ad creatives paired with precise interest and lookalike audiences.'],
                ['icon' => 'ri-funds-line', 'title' => 'Conversion Tracking & ROAS Tuning', 'text' => 'Setup Meta Pixel, CAPI, and Google Tag Manager to track true cost per acquisition.'],
            ],
            'work' => [
                ['label' => 'PPC', 'name' => 'Google Search Lead Campaign', 'text' => 'Generated 140 qualified inquiries at $12 CPA for service firm.'],
                ['label' => 'Meta', 'name' => 'E-Commerce Meta Ad Scaling', 'text' => 'Achieved 4.2X ROAS scaling monthly ad budget to $15k.'],
                ['label' => 'Retargeting', 'name' => 'Cart Abandonment Ad Funnel', 'text' => 'Recovered 22% of abandoned carts via dynamic Facebook ads.'],
            ],
        ],
        'social-media-marketing-growth' => [
            'category' => 'marketing',
            'title' => 'Social Media Marketing',
            'headline' => 'Build A Loyal Audience & Transform Social Channels Into Sales Engines',
            'intro' => 'We manage Instagram, Facebook, LinkedIn, and TikTok channels with strategic content calendars, visual design, and community growth.',
            'features' => [
                ['icon' => 'ri-calendar-todo-line', 'title' => 'Monthly Content Calendar', 'text' => 'Planned posts combining promotional offers, educational carousels, reels, and stories.'],
                ['icon' => 'ri-image-line', 'title' => 'Branded Graphic & Video Assets', 'text' => 'High-quality post graphics, short video reels, and engaging captions.'],
                ['icon' => 'ri-line-chart-line', 'title' => 'Growth & Community Engagement', 'text' => 'Proactive follower outreach, comment management, and monthly performance reports.'],
            ],
            'work' => [
                ['label' => 'Instagram', 'name' => 'Restaurant Brand Channel', 'text' => 'Grew active Instagram followers from 1.2k to 14.5k in 6 months.'],
                ['label' => 'LinkedIn', 'name' => 'B2B Founder Personal Brand', 'text' => 'Positioned CEO as industry thought leader driving inbound deals.'],
                ['label' => 'TikTok', 'name' => 'Viral Product Video Campaign', 'text' => 'Short video strategy generating 500k+ organic views.'],
            ],
        ],
        'content-strategy' => [
            'category' => 'marketing',
            'title' => 'Content Strategy',
            'headline' => 'Authority-Building Content Strategy That Converts Readers Into Clients',
            'intro' => 'We create content roadmaps, SEO blog articles, whitepapers, case studies, and lead magnets that establish industry leadership.',
            'features' => [
                ['icon' => 'ri-article-line', 'title' => 'Keyword Content Mapping', 'text' => 'Map top-of-funnel educational topics to bottom-of-funnel decision content.'],
                ['icon' => 'ri-edit-line', 'title' => 'Professional Copywriting', 'text' => 'Well-researched, engaging articles written by experienced technical and business writers.'],
                ['icon' => 'ri-book-open-line', 'title' => 'Lead Magnets & eBooks', 'text' => 'Downloadable guides and checklists designed to capture email leads.'],
            ],
            'work' => [
                ['label' => 'Blog', 'name' => 'SaaS Educational Knowledge Hub', 'text' => 'Published 24 long-form guides driving 15k monthly readers.'],
                ['label' => 'Case Study', 'name' => 'Enterprise Customer Success Stories', 'text' => 'Written case study library used by sales team to close enterprise deals.'],
                ['label' => 'Guide', 'name' => 'Industry Trends PDF Report', 'text' => 'Gated report capturing 800+ executive email downloads.'],
            ],
        ],
        'email-marketing-automation' => [
            'category' => 'marketing',
            'title' => 'Email Marketing & Automation',
            'headline' => 'Automated Email Campaigns That Nurture Leads & Repeat Sales',
            'intro' => 'We design email templates and build automated drip sequences in Mailchimp, Klaviyo, ActiveCampaign, or Brevo.',
            'features' => [
                ['icon' => 'ri-mail-send-line', 'title' => 'Automated Drip Sequences', 'text' => 'Instant welcome series, lead lead-nurture flows, and post-purchase follow-ups.'],
                ['icon' => 'ri-layout-row-line', 'title' => 'Branded Email Layouts', 'text' => 'Responsive, mobile-friendly HTML email templates for newsletters and promotions.'],
                ['icon' => 'ri-bar-chart-grouped-line', 'title' => 'A/B Testing & Audience Segmentation', 'text' => 'Segment lists by purchase history, location, and engagement for maximum open rates.'],
            ],
            'work' => [
                ['label' => 'Klaviyo', 'name' => 'E-Commerce Abandoned Cart Sequence', 'text' => '3-email flow recovering $18k in monthly lost revenue.'],
                ['label' => 'Nurture', 'name' => 'B2B Lead Nurturing Campaign', 'text' => '6-week automated email sequence warming cold web leads.'],
                ['label' => 'Newsletter', 'name' => 'Weekly Industry Insights Letter', 'text' => 'Maintained 42% average open rate across 20k subscribers.'],
            ],
        ],
    ],
];
