<?php

return [
    'categories' => [
        'branding' => [
            'label' => 'Branding & Design',
            'badge' => 'Creative Service',
            'icon' => 'ri-paint-brush-line',
            'image' => 'portfolio_section.png',
            'hero_kicker' => 'Design for brands',
            'hero_title' => 'Sharp visuals that make every customer touchpoint feel consistent.',
            'hero_text' => 'From first concepts to final delivery, every asset is prepared for practical use across web, print, and social media.',
            'work_images' => ['portfolio_section.png', 'our_services_2.png', 'hero.png'],
            'process' => ['Discovery', 'Concepts', 'Design', 'Refine', 'Delivery'],
            'metrics' => [
                ['value' => '3X', 'label' => 'Visual Recall'],
                ['value' => '48h', 'label' => 'First Draft'],
                ['value' => '100%', 'label' => 'Source Files'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Starter Creative', 'price' => '$149', 'tag' => 'Launch', 'features' => ['2 design concepts', '2 revision rounds', 'Web-ready files', 'Basic usage guide']],
                ['name' => 'Growth Creative', 'price' => '$299', 'tag' => 'Popular', 'features' => ['4 design concepts', '4 revision rounds', 'Print-ready files', 'Social preview mockup']],
                ['name' => 'Premium Creative', 'price' => '$499', 'tag' => 'Complete', 'features' => ['6 design concepts', 'Full source files', 'Stationery or social kit', 'Priority delivery']],
            ],
        ],
        'web' => [
            'label' => 'Website Development',
            'badge' => 'Web Service',
            'icon' => 'ri-global-line',
            'image' => 'our_services.png',
            'hero_kicker' => 'Conversion-ready builds',
            'hero_title' => 'Modern websites built for speed, trust, and customer action.',
            'hero_text' => 'We design clean user journeys, responsive layouts, and practical admin flows that are easy to manage after launch.',
            'work_images' => ['our_services.png', 'hero.png', 'contact_us.png'],
            'process' => ['Plan', 'Wireframe', 'Develop', 'Test', 'Launch'],
            'metrics' => [
                ['value' => '95+', 'label' => 'Speed Score'],
                ['value' => '100%', 'label' => 'Responsive'],
                ['value' => 'SEO', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Starter Website', 'price' => '$399', 'tag' => 'Launch', 'features' => ['Up to 5 pages', 'Responsive design', 'Contact form', 'Basic SEO setup']],
                ['name' => 'Business Website', 'price' => '$899', 'tag' => 'Popular', 'features' => ['Up to 10 pages', 'CMS setup', 'Speed optimization', 'Analytics integration']],
                ['name' => 'Custom Platform', 'price' => '$1,499+', 'tag' => 'Advanced', 'features' => ['Custom features', 'Admin dashboard', 'API integrations', 'Launch support']],
            ],
        ],
        'app' => [
            'label' => 'Mobile App Development',
            'badge' => 'App Service',
            'icon' => 'ri-smartphone-line',
            'image' => 'our_services_2.png',
            'hero_kicker' => 'Mobile product delivery',
            'hero_title' => 'App experiences shaped around simple flows and repeat usage.',
            'hero_text' => 'We plan screens, build core features, and prepare mobile products that feel clear, fast, and brand-aligned.',
            'work_images' => ['our_services_2.png', 'our_services.png', 'hero.png'],
            'process' => ['Scope', 'Prototype', 'Build', 'QA', 'Release'],
            'metrics' => [
                ['value' => '2X', 'label' => 'Faster Flow'],
                ['value' => 'iOS', 'label' => 'Ready'],
                ['value' => 'Android', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'App Prototype', 'price' => '$799', 'tag' => 'Validate', 'features' => ['Core screen designs', 'Clickable prototype', 'User flow map', 'Handoff files']],
                ['name' => 'MVP App', 'price' => '$1,899', 'tag' => 'Popular', 'features' => ['Core app build', 'Backend connection', 'Testing support', 'Store-ready assets']],
                ['name' => 'Full App Product', 'price' => '$3,499+', 'tag' => 'Scale', 'features' => ['Advanced features', 'Admin dashboard', 'API integrations', 'Maintenance plan']],
            ],
        ],
        'software' => [
            'label' => 'Software & ERP',
            'badge' => 'Business Systems',
            'icon' => 'ri-tools-line',
            'image' => 'hero.png',
            'hero_kicker' => 'Operational software',
            'hero_title' => 'Custom systems that organize work and reduce manual effort.',
            'hero_text' => 'We build dashboards, records, workflows, reports, and team tools around the way your business actually operates.',
            'work_images' => ['hero.png', 'our_services.png', 'portfolio_section.png'],
            'process' => ['Audit', 'Flow Design', 'Development', 'Testing', 'Training'],
            'metrics' => [
                ['value' => '40%', 'label' => 'Less Manual Work'],
                ['value' => 'Live', 'label' => 'Reports'],
                ['value' => 'Role', 'label' => 'Access'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'System Starter', 'price' => '$999', 'tag' => 'Internal', 'features' => ['Core modules', 'User roles', 'Basic reports', 'Setup support']],
                ['name' => 'Business System', 'price' => '$2,499', 'tag' => 'Popular', 'features' => ['Multiple modules', 'Dashboard reports', 'Workflow automation', 'Data import']],
                ['name' => 'Enterprise Suite', 'price' => '$4,999+', 'tag' => 'Scale', 'features' => ['Custom ERP/CRM', 'Advanced permissions', 'Integrations', 'Training and support']],
            ],
        ],
        'cloud' => [
            'label' => 'Backend & Cloud',
            'badge' => 'Infrastructure',
            'icon' => 'ri-cloud-line',
            'image' => 'hero.png',
            'hero_kicker' => 'Reliable infrastructure',
            'hero_title' => 'Backends, APIs, and cloud setups that keep products moving.',
            'hero_text' => 'We design secure server-side foundations, automate deployment, and keep the technical base easy to maintain.',
            'work_images' => ['hero.png', 'contact_us.png', 'our_services.png'],
            'process' => ['Architecture', 'Build', 'Secure', 'Deploy', 'Monitor'],
            'metrics' => [
                ['value' => '99%', 'label' => 'Uptime Goal'],
                ['value' => 'API', 'label' => 'Ready'],
                ['value' => 'SSL', 'label' => 'Secure'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Backend Starter', 'price' => '$499', 'tag' => 'Setup', 'features' => ['API setup', 'Database schema', 'Auth basics', 'Deployment notes']],
                ['name' => 'Cloud Launch', 'price' => '$1,299', 'tag' => 'Popular', 'features' => ['Cloud server setup', 'CI/CD pipeline', 'Security hardening', 'Monitoring setup']],
                ['name' => 'Scale Infrastructure', 'price' => '$2,499+', 'tag' => 'Scale', 'features' => ['Advanced architecture', 'Load-ready setup', 'Backups', 'Ongoing optimization']],
            ],
        ],
        'advanced' => [
            'label' => 'Advanced / Modern Services',
            'badge' => 'Modern Automation',
            'icon' => 'ri-robot-line',
            'image' => 'our_services_2.png',
            'hero_kicker' => 'Smarter workflows',
            'hero_title' => 'Automation, analytics, and product systems for modern teams.',
            'hero_text' => 'We connect tools, reduce repeat tasks, and create dashboards that turn scattered operations into clear action.',
            'work_images' => ['our_services_2.png', 'hero.png', 'portfolio_section.png'],
            'process' => ['Map', 'Prototype', 'Integrate', 'Automate', 'Improve'],
            'metrics' => [
                ['value' => '60%', 'label' => 'Time Saved'],
                ['value' => 'AI', 'label' => 'Ready'],
                ['value' => 'Live', 'label' => 'Dashboards'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Automation Starter', 'price' => '$699', 'tag' => 'Quick Win', 'features' => ['Workflow map', '1 automation flow', 'Tool connection', 'Basic testing']],
                ['name' => 'Smart Operations', 'price' => '$1,799', 'tag' => 'Popular', 'features' => ['Multiple workflows', 'Dashboard setup', 'API connections', 'Team handover']],
                ['name' => 'Product Innovation', 'price' => '$3,499+', 'tag' => 'Scale', 'features' => ['SaaS planning', 'Advanced automations', 'Analytics layer', 'Ongoing iteration']],
            ],
        ],
        'marketing' => [
            'label' => 'Digital Marketing',
            'badge' => 'Growth Service',
            'icon' => 'ri-megaphone-line',
            'image' => 'contact_us.png',
            'hero_kicker' => 'Traffic and leads',
            'hero_title' => 'Campaign systems that attract, convert, and keep improving.',
            'hero_text' => 'We combine SEO, paid campaigns, content, and email flows into practical growth activity your business can measure.',
            'work_images' => ['contact_us.png', 'portfolio_section.png', 'hero.png'],
            'process' => ['Research', 'Plan', 'Launch', 'Measure', 'Optimize'],
            'metrics' => [
                ['value' => '3X', 'label' => 'Reach Goal'],
                ['value' => 'SEO', 'label' => 'Ready'],
                ['value' => 'PPC', 'label' => 'Ready'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Marketing Starter', 'price' => '$299', 'tag' => 'Launch', 'features' => ['Audit and plan', 'Keyword direction', 'Basic content plan', 'Monthly reporting']],
                ['name' => 'Growth Campaign', 'price' => '$799', 'tag' => 'Popular', 'features' => ['SEO and ads setup', 'Campaign creatives', 'Landing page guidance', 'Performance reports']],
                ['name' => 'Scale Marketing', 'price' => '$1,499+', 'tag' => 'Scale', 'features' => ['Multi-channel strategy', 'Content calendar', 'Conversion tracking', 'Optimization sprints']],
            ],
        ],
        'creative' => [
            'label' => 'Graphic & Creative',
            'badge' => 'Creative Production',
            'icon' => 'ri-image-line',
            'image' => 'portfolio_section.png',
            'hero_kicker' => 'Visual content',
            'hero_title' => 'Campaign-ready creative assets for stronger everyday marketing.',
            'hero_text' => 'We produce practical digital and print assets that keep launches, posts, decks, and campaigns looking polished.',
            'work_images' => ['portfolio_section.png', 'contact_us.png', 'our_services_2.png'],
            'process' => ['Brief', 'Direction', 'Design', 'Revise', 'Export'],
            'metrics' => [
                ['value' => '30+', 'label' => 'Asset Types'],
                ['value' => 'Fast', 'label' => 'Delivery'],
                ['value' => 'HD', 'label' => 'Exports'],
                ['value' => '24/7', 'label' => 'Support'],
            ],
            'packages' => [
                ['name' => 'Creative Starter', 'price' => '$99', 'tag' => 'Small Batch', 'features' => ['3 static designs', '1 revision round', 'Web-ready exports', 'Brand matching']],
                ['name' => 'Campaign Pack', 'price' => '$249', 'tag' => 'Popular', 'features' => ['10 static designs', 'Ad size variants', 'Source files', 'Fast revisions']],
                ['name' => 'Monthly Creative', 'price' => '$599+', 'tag' => 'Ongoing', 'features' => ['Monthly asset plan', 'Social and ad creatives', 'Priority queue', 'Performance updates']],
            ],
        ],
        'support' => [
            'label' => 'Maintenance & Support',
            'badge' => 'Ongoing Care',
            'icon' => 'ri-settings-2-line',
            'image' => 'contact_us.png',
            'hero_kicker' => 'Reliable support',
            'hero_title' => 'Maintenance plans that keep your website and systems healthy.',
            'hero_text' => 'We handle updates, fixes, backups, and performance checks so your digital platforms keep running smoothly.',
            'work_images' => ['contact_us.png', 'hero.png', 'our_services.png'],
            'process' => ['Audit', 'Fix', 'Update', 'Secure', 'Report'],
            'metrics' => [
                ['value' => '24/7', 'label' => 'Monitoring'],
                ['value' => '99%', 'label' => 'Uptime Goal'],
                ['value' => 'Safe', 'label' => 'Backups'],
                ['value' => 'Fast', 'label' => 'Fixes'],
            ],
            'packages' => [
                ['name' => 'Basic Care', 'price' => '$99/mo', 'tag' => 'Light', 'features' => ['Monthly updates', 'Backup check', 'Bug fixes', 'Email support']],
                ['name' => 'Business Care', 'price' => '$249/mo', 'tag' => 'Popular', 'features' => ['Weekly checks', 'Priority fixes', 'Security patches', 'Performance report']],
                ['name' => 'Priority Support', 'price' => '$599/mo', 'tag' => 'Critical', 'features' => ['Fast response', 'Monitoring setup', 'Ongoing improvements', 'Dedicated support hours']],
            ],
        ],
    ],

    'pages' => [
        'logo-design' => [
            'category' => 'branding',
            'title' => 'Logo Design',
            'headline' => 'Get Appealing Logo Designs That Make Your Brand Easy To Remember',
            'intro' => 'We create modern logo concepts, brand marks, stationery previews, and final files that work across web, print, and social media.',
            'image' => 'portfolio_section.png',
            'work_images' => ['portfolio_section.png', 'our_services_2.png', 'hero.png'],
            'package_label' => 'Logo Design Packages',
            'features' => [
                ['icon' => 'ri-paint-brush-line', 'title' => 'Custom Logo Concepts', 'text' => 'Unique logo directions shaped around your business, audience, and visual style.'],
                ['icon' => 'ri-palette-line', 'title' => 'Color And Typography', 'text' => 'Simple color and font direction so the logo feels complete in real usage.'],
                ['icon' => 'ri-folder-download-line', 'title' => 'Final File Delivery', 'text' => 'Web and print-ready exports prepared for websites, profiles, stationery, and marketing.'],
            ],
            'work' => [
                ['label' => 'Logo', 'name' => 'Dog World', 'text' => 'Friendly logo direction for a pet-focused brand with strong recall.'],
                ['label' => 'Logo', 'name' => 'Realty Solutions', 'text' => 'Clean property brand mark designed for credibility and local trust.'],
                ['label' => 'Mockup', 'name' => 'AM Autos Brand Kit', 'text' => 'Automotive logo system shown across business and campaign assets.'],
            ],
            'packages' => [
                ['name' => 'Starter Logo Package', 'price' => '$149', 'tag' => 'New Business', 'features' => ['2 logo concepts', '2 revision rounds', 'Primary logo files', 'PNG and JPG delivery']],
                ['name' => 'Growth Logo Package', 'price' => '$299', 'tag' => 'Most Popular', 'features' => ['4 logo concepts', '4 revision rounds', 'Color palette', 'Business card mockup']],
                ['name' => 'Premium Graphics Package', 'price' => '$499', 'tag' => 'Full Kit', 'features' => ['6 logo concepts', 'Stationery design', 'Banner design set', 'Editable source files']],
            ],
        ],
        'brand-identity' => [
            'category' => 'branding',
            'title' => 'Brand Identity',
            'headline' => 'Build A Powerful Brand Identity Customers Instantly Recognize',
            'intro' => 'We create complete identity systems including logo direction, colors, typography, stationery, guidelines, and visual assets.',
            'image' => 'our_services_2.png',
            'work_images' => ['our_services_2.png', 'portfolio_section.png', 'hero.png'],
            'package_label' => 'Brand Identity Packages',
            'features' => [
                ['icon' => 'ri-compass-3-line', 'title' => 'Brand Strategy', 'text' => 'Define the visual direction, positioning, and customer-facing personality of your brand.'],
                ['icon' => 'ri-contrast-drop-2-line', 'title' => 'Identity System', 'text' => 'Logo usage, colors, typography, stationery, and social assets built as one system.'],
                ['icon' => 'ri-booklet-line', 'title' => 'Brand Guidelines', 'text' => 'Clear rules that help your team keep the brand consistent after delivery.'],
            ],
            'work' => [
                ['label' => 'Identity', 'name' => 'Fresh Cafe Identity', 'text' => 'Logo, color, and type direction for a warm local launch.'],
                ['label' => 'Stationery', 'name' => 'Realty Brand Suite', 'text' => 'Business card, letterhead, and digital identity previews.'],
                ['label' => 'System', 'name' => 'AM Autos Visual System', 'text' => 'Complete visual language for a bold service business.'],
            ],
            'packages' => [
                ['name' => 'Starter Identity', 'price' => '$249', 'tag' => 'Launch Kit', 'features' => ['Logo refinement', 'Color palette', 'Font pairing', 'Social profile mockup']],
                ['name' => 'Professional Identity', 'price' => '$599', 'tag' => 'Popular', 'features' => ['Logo system', 'Brand guidelines', 'Business card set', 'Letterhead design']],
                ['name' => 'Complete Brand System', 'price' => '$999', 'tag' => 'Full System', 'features' => ['Brand strategy board', 'Stationery suite', 'Social media kit', 'Mini brand book']],
            ],
        ],
        'business-cards' => [
            'category' => 'branding',
            'title' => 'Business Card Design',
            'headline' => 'Business Card Designs That Make Your First Impression Feel Premium',
            'intro' => 'We create clean, print-ready business cards with strong typography, readable contact details, and brand-aligned layouts.',
            'features' => [
                ['icon' => 'ri-bank-card-line', 'title' => 'Front and Back Layouts', 'text' => 'Professional card layouts prepared for print and digital sharing.'],
                ['icon' => 'ri-qr-code-line', 'title' => 'Smart Contact Details', 'text' => 'QR, phone, email, web, and social details arranged for fast scanning.'],
                ['icon' => 'ri-printer-line', 'title' => 'Print-Ready Files', 'text' => 'Final files exported with practical bleed, spacing, and format support.'],
            ],
            'work' => [
                ['label' => 'Stationery', 'name' => 'Executive Card Set', 'text' => 'Minimal card concept with clean hierarchy and premium color accents.'],
                ['label' => 'Print', 'name' => 'Founder Contact Card', 'text' => 'Bold personal brand card with QR scan and social details.'],
                ['label' => 'Identity', 'name' => 'Team Card System', 'text' => 'Reusable card layout for departments, roles, and branches.'],
            ],
        ],
        'social-media-kit' => [
            'category' => 'branding',
            'title' => 'Social Media Kit',
            'headline' => 'Branded Social Media Kits For Consistent Daily Posting',
            'intro' => 'We design post templates, profile graphics, banners, and campaign assets that keep your social presence polished.',
            'features' => [
                ['icon' => 'ri-layout-grid-line', 'title' => 'Post Templates', 'text' => 'Reusable templates for announcements, offers, tips, and testimonials.'],
                ['icon' => 'ri-image-edit-line', 'title' => 'Profile Assets', 'text' => 'Cover images, profile graphics, and highlight visuals shaped to your brand.'],
                ['icon' => 'ri-megaphone-line', 'title' => 'Campaign Graphics', 'text' => 'Launch-ready creative for promotions, ads, and seasonal campaigns.'],
            ],
            'work' => [
                ['label' => 'Instagram', 'name' => 'Retail Launch Grid', 'text' => 'Nine-post visual system for a product launch campaign.'],
                ['label' => 'Facebook', 'name' => 'Service Promo Kit', 'text' => 'Cover, story, and feed templates for local service promotion.'],
                ['label' => 'Brand Kit', 'name' => 'Monthly Content Set', 'text' => 'Reusable visual system for repeat social campaigns.'],
            ],
        ],
        'ui-ux-design' => [
            'category' => 'branding',
            'title' => 'UI/UX Design',
            'headline' => 'Clear UI/UX Design For Websites, Apps, And Digital Products',
            'intro' => 'We plan user flows, structure screens, and design polished interfaces that make digital products easier to use.',
            'features' => [
                ['icon' => 'ri-flow-chart', 'title' => 'User Flow Planning', 'text' => 'Clear journeys for signups, purchases, bookings, and dashboards.'],
                ['icon' => 'ri-layout-2-line', 'title' => 'Screen Design', 'text' => 'Responsive interface designs for web and mobile experiences.'],
                ['icon' => 'ri-mouse-line', 'title' => 'Clickable Prototypes', 'text' => 'Interactive previews that help teams test ideas before development.'],
            ],
            'work' => [
                ['label' => 'Website UI', 'name' => 'SaaS Landing Flow', 'text' => 'Conversion-focused product page and signup journey.'],
                ['label' => 'App UI', 'name' => 'Booking App Screens', 'text' => 'Clean mobile booking flow with simple navigation.'],
                ['label' => 'Dashboard', 'name' => 'Analytics Workspace', 'text' => 'Data-heavy interface shaped for scanning and action.'],
            ],
        ],
        'packaging-design' => [
            'category' => 'branding',
            'title' => 'Packaging Design',
            'headline' => 'Packaging Design That Makes Products Look Shelf-Ready',
            'intro' => 'We create product packaging concepts, labels, sleeves, and box visuals that support your brand and sales goals.',
            'features' => [
                ['icon' => 'ri-box-3-line', 'title' => 'Box And Label Concepts', 'text' => 'Packaging directions for retail, ecommerce, and launch previews.'],
                ['icon' => 'ri-palette-line', 'title' => 'Brand-Aligned Visuals', 'text' => 'Color, typography, and layout choices that fit your identity.'],
                ['icon' => 'ri-file-paper-2-line', 'title' => 'Production Handoff', 'text' => 'Organized files and mockups for printer or supplier discussion.'],
            ],
            'work' => [
                ['label' => 'Retail', 'name' => 'Premium Box Concept', 'text' => 'Bold front-facing packaging direction for a new product.'],
                ['label' => 'Label', 'name' => 'Bottle Label System', 'text' => 'Reusable label design with variants for multiple flavors.'],
                ['label' => 'Ecommerce', 'name' => 'Mailer Box Mockup', 'text' => 'Shipping-friendly branded packaging for online orders.'],
            ],
        ],
        'business-websites' => [
            'category' => 'web',
            'title' => 'Business Websites',
            'headline' => 'Professional Business Websites That Build Trust And Generate Leads',
            'intro' => 'We design and develop company websites, service pages, portfolios, and landing pages for businesses that need a stronger online presence.',
            'features' => [
                ['icon' => 'ri-pages-line', 'title' => 'Service Pages', 'text' => 'Clear pages for your offers, process, team, and contact flow.'],
                ['icon' => 'ri-smartphone-line', 'title' => 'Responsive Layout', 'text' => 'A polished experience across mobile, tablet, and desktop.'],
                ['icon' => 'ri-search-eye-line', 'title' => 'SEO Structure', 'text' => 'Readable content structure and metadata basics for search visibility.'],
            ],
            'work' => [
                ['label' => 'Company Site', 'name' => 'Consulting Website', 'text' => 'Service-led business website with clear lead capture.'],
                ['label' => 'Portfolio', 'name' => 'Studio Showcase', 'text' => 'Project-focused portfolio with inquiry-ready layout.'],
                ['label' => 'Landing Page', 'name' => 'Campaign Lead Page', 'text' => 'Single-page flow built for conversions and tracking.'],
            ],
        ],
        'ecommerce-websites' => [
            'category' => 'web',
            'title' => 'E-commerce Websites',
            'headline' => 'Online Stores Designed To Sell Products Clearly And Quickly',
            'intro' => 'We build ecommerce websites with product catalogs, shopping carts, checkout flows, payment setup, and practical management tools.',
            'features' => [
                ['icon' => 'ri-shopping-cart-line', 'title' => 'Product Catalog', 'text' => 'Organized product pages with categories, filters, and detail layouts.'],
                ['icon' => 'ri-bank-card-line', 'title' => 'Checkout Setup', 'text' => 'Cart, checkout, payment, and order-flow setup for smooth purchases.'],
                ['icon' => 'ri-dashboard-3-line', 'title' => 'Store Management', 'text' => 'Admin-ready setup for products, orders, content, and updates.'],
            ],
            'work' => [
                ['label' => 'Retail', 'name' => 'Fashion Storefront', 'text' => 'Modern product browsing experience for a growing online brand.'],
                ['label' => 'Checkout', 'name' => 'Fast Purchase Flow', 'text' => 'Reduced checkout friction with clear payment steps.'],
                ['label' => 'Catalog', 'name' => 'Multi-Category Store', 'text' => 'Product hierarchy for search, categories, and promotions.'],
            ],
        ],
        'custom-web-apps' => [
            'category' => 'web',
            'title' => 'Custom Web Applications',
            'headline' => 'Custom Web Apps For Dashboards, Portals, CRMs, And Business Tools',
            'intro' => 'We build browser-based systems that manage users, data, workflows, approvals, and reports around your business operations.',
            'features' => [
                ['icon' => 'ri-dashboard-line', 'title' => 'Dashboards', 'text' => 'Action-focused panels for metrics, records, and workflow status.'],
                ['icon' => 'ri-user-settings-line', 'title' => 'User Roles', 'text' => 'Role-based access for admins, staff, customers, and partners.'],
                ['icon' => 'ri-database-2-line', 'title' => 'Data Management', 'text' => 'Structured records, search, filters, exports, and reporting flows.'],
            ],
            'work' => [
                ['label' => 'Portal', 'name' => 'Client Workspace', 'text' => 'Login-based portal for documents, updates, and communication.'],
                ['label' => 'Dashboard', 'name' => 'Sales Operations App', 'text' => 'Lead tracking, pipeline actions, and daily reporting.'],
                ['label' => 'Workflow', 'name' => 'Approval System', 'text' => 'Multi-step approvals with notifications and audit history.'],
            ],
        ],
        'cms-development' => [
            'category' => 'web',
            'title' => 'CMS Development',
            'headline' => 'CMS Websites Your Team Can Update Without Developer Help',
            'intro' => 'We build WordPress and custom CMS solutions so teams can manage pages, posts, media, services, and core content easily.',
            'features' => [
                ['icon' => 'ri-edit-box-line', 'title' => 'Editable Pages', 'text' => 'Structured content blocks for repeat updates and new pages.'],
                ['icon' => 'ri-folder-settings-line', 'title' => 'Admin Setup', 'text' => 'Simple admin flows for posts, services, images, and settings.'],
                ['icon' => 'ri-shield-check-line', 'title' => 'Secure Foundation', 'text' => 'Clean setup with updates, roles, backups, and best practices.'],
            ],
            'work' => [
                ['label' => 'CMS', 'name' => 'Corporate Content Hub', 'text' => 'Editable pages and posts for a service business.'],
                ['label' => 'WordPress', 'name' => 'Blog And Lead Site', 'text' => 'Marketing site with publishing tools and inquiry forms.'],
                ['label' => 'Custom CMS', 'name' => 'Service Manager', 'text' => 'Admin system for managing service content and media.'],
            ],
        ],
        'website-redesign' => [
            'category' => 'web',
            'title' => 'Website Redesign',
            'headline' => 'Website Redesigns That Improve Trust, Speed, And Conversions',
            'intro' => 'We refresh outdated websites with stronger visuals, cleaner navigation, better copy flow, and improved technical performance.',
            'features' => [
                ['icon' => 'ri-refresh-line', 'title' => 'Visual Refresh', 'text' => 'Modern styling while preserving what already works for your brand.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Performance Fixes', 'text' => 'Speed, structure, and mobile improvements for a smoother experience.'],
                ['icon' => 'ri-route-line', 'title' => 'Conversion Flow', 'text' => 'Clearer calls to action, sections, and inquiry paths.'],
            ],
            'work' => [
                ['label' => 'Revamp', 'name' => 'Service Website Refresh', 'text' => 'Modernized homepage and service pages for better credibility.'],
                ['label' => 'Performance', 'name' => 'Speed Cleanup', 'text' => 'Cleaner assets and layout fixes for faster browsing.'],
                ['label' => 'UX', 'name' => 'Navigation Rebuild', 'text' => 'Simplified menus and page flow for easier discovery.'],
            ],
        ],
        'android-apps' => [
            'category' => 'app',
            'title' => 'Android Apps',
            'headline' => 'Android App Development For Business, Booking, And Customer Workflows',
            'intro' => 'We design and build Android apps with clean screens, practical features, backend connections, and release-ready assets.',
            'features' => [
                ['icon' => 'ri-android-line', 'title' => 'Native-Friendly UX', 'text' => 'Android-focused interface patterns and smooth user flows.'],
                ['icon' => 'ri-notification-3-line', 'title' => 'Core Features', 'text' => 'Login, forms, bookings, notifications, payments, and dashboards.'],
                ['icon' => 'ri-upload-cloud-line', 'title' => 'Release Support', 'text' => 'Store assets, build preparation, and launch guidance.'],
            ],
            'work' => [
                ['label' => 'Android', 'name' => 'Service Booking App', 'text' => 'Simple booking flow with customer profiles and notifications.'],
                ['label' => 'Business', 'name' => 'Team Field App', 'text' => 'Mobile operations app for staff updates and task status.'],
                ['label' => 'Customer', 'name' => 'Loyalty App', 'text' => 'Branded customer experience for offers and repeat purchases.'],
            ],
        ],
        'ios-apps' => [
            'category' => 'app',
            'title' => 'iOS Apps',
            'headline' => 'iOS App Experiences Designed For Clarity And Premium Feel',
            'intro' => 'We create polished iOS app interfaces and product flows for service businesses, startups, and customer platforms.',
            'features' => [
                ['icon' => 'ri-apple-line', 'title' => 'iOS-Aligned Design', 'text' => 'Clean app structure, readable screens, and native-style interactions.'],
                ['icon' => 'ri-shield-user-line', 'title' => 'Secure Access', 'text' => 'Login, account areas, role access, and protected user data flows.'],
                ['icon' => 'ri-store-2-line', 'title' => 'App Store Prep', 'text' => 'Launch assets, screenshots, and release support planning.'],
            ],
            'work' => [
                ['label' => 'iOS', 'name' => 'Wellness Booking App', 'text' => 'Elegant scheduling and account flow for recurring appointments.'],
                ['label' => 'Startup', 'name' => 'MVP Product App', 'text' => 'Prototype-to-build process for early product validation.'],
                ['label' => 'Brand', 'name' => 'Customer Portal App', 'text' => 'Premium mobile portal for account and service updates.'],
            ],
        ],
        'cross-platform-apps' => [
            'category' => 'app',
            'title' => 'Cross-Platform Apps',
            'headline' => 'Cross-Platform Apps That Reach iOS And Android From One Build',
            'intro' => 'We create Flutter and React Native app experiences that help businesses launch faster across major mobile platforms.',
            'features' => [
                ['icon' => 'ri-stack-line', 'title' => 'Shared Codebase', 'text' => 'One product foundation for faster updates across mobile platforms.'],
                ['icon' => 'ri-smartphone-line', 'title' => 'Consistent UI', 'text' => 'Brand-aligned screens that feel polished on iOS and Android.'],
                ['icon' => 'ri-links-line', 'title' => 'Backend Connections', 'text' => 'API, database, payment, and notification integration support.'],
            ],
            'work' => [
                ['label' => 'Flutter', 'name' => 'Retail App MVP', 'text' => 'Cross-platform store app with catalog and account screens.'],
                ['label' => 'React Native', 'name' => 'Booking Product', 'text' => 'Scheduling app shipped across iOS and Android.'],
                ['label' => 'Operations', 'name' => 'Internal Team App', 'text' => 'Staff workflow app with tasks, forms, and reporting.'],
            ],
        ],
        'app-ui-ux-design' => [
            'category' => 'app',
            'title' => 'App UI/UX Design',
            'headline' => 'Mobile App UI/UX Design That Makes Every Tap Feel Obvious',
            'intro' => 'We plan and design app screens, flows, and prototypes before development so the final product feels easier to use.',
            'features' => [
                ['icon' => 'ri-drag-move-line', 'title' => 'Screen Flow', 'text' => 'Logical user journeys for onboarding, accounts, bookings, and purchases.'],
                ['icon' => 'ri-pencil-ruler-2-line', 'title' => 'Visual System', 'text' => 'Mobile components, typography, colors, spacing, and icon style.'],
                ['icon' => 'ri-play-circle-line', 'title' => 'Prototype', 'text' => 'Clickable app preview for feedback before development begins.'],
            ],
            'work' => [
                ['label' => 'Prototype', 'name' => 'Customer Booking Flow', 'text' => 'Step-by-step app flow with clear calls to action.'],
                ['label' => 'UI Kit', 'name' => 'Mobile Component Set', 'text' => 'Reusable buttons, cards, inputs, and screen patterns.'],
                ['label' => 'UX', 'name' => 'Onboarding Redesign', 'text' => 'Fewer steps and clearer first-time user experience.'],
            ],
        ],
        'app-maintenance' => [
            'category' => 'app',
            'title' => 'App Maintenance',
            'headline' => 'App Maintenance That Keeps Mobile Products Stable And Updated',
            'intro' => 'We help maintain mobile apps with bug fixes, updates, performance checks, compatibility support, and feature improvements.',
            'features' => [
                ['icon' => 'ri-bug-line', 'title' => 'Bug Fixing', 'text' => 'Issue review, priority fixes, and practical release support.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Performance Checks', 'text' => 'Optimization for loading, responsiveness, and app stability.'],
                ['icon' => 'ri-refresh-line', 'title' => 'Version Updates', 'text' => 'Platform compatibility updates and planned feature enhancements.'],
            ],
            'work' => [
                ['label' => 'Support', 'name' => 'Monthly App Care', 'text' => 'Ongoing maintenance plan for a customer-facing app.'],
                ['label' => 'Performance', 'name' => 'Loading Speed Fix', 'text' => 'Reduced app delays and smoother interaction flow.'],
                ['label' => 'Release', 'name' => 'Store Update Prep', 'text' => 'Compatibility updates and release checklist support.'],
            ],
        ],
        'erp-systems' => [
            'category' => 'software',
            'title' => 'ERP Systems',
            'headline' => 'ERP Systems That Connect Teams, Records, And Daily Operations',
            'intro' => 'We build ERP modules for sales, inventory, HR, finance, reporting, and operational workflows tailored to your business.',
            'features' => [
                ['icon' => 'ri-building-4-line', 'title' => 'Business Modules', 'text' => 'Sales, finance, HR, inventory, and branch workflows in one system.'],
                ['icon' => 'ri-bar-chart-box-line', 'title' => 'Live Reports', 'text' => 'Dashboards and exports for faster business decisions.'],
                ['icon' => 'ri-lock-password-line', 'title' => 'Role Access', 'text' => 'Secure access levels for staff, managers, and administrators.'],
            ],
            'work' => [
                ['label' => 'ERP', 'name' => 'Operations Control Center', 'text' => 'Central dashboard for departments, reports, and tasks.'],
                ['label' => 'Inventory', 'name' => 'Stock And Sales Flow', 'text' => 'Connected sales and inventory reporting workflow.'],
                ['label' => 'Finance', 'name' => 'Revenue Reporting Suite', 'text' => 'Daily finance summary with branch-level filters.'],
            ],
        ],
        'crm-systems' => [
            'category' => 'software',
            'title' => 'CRM Systems',
            'headline' => 'CRM Systems For Leads, Follow-Ups, Pipelines, And Customer History',
            'intro' => 'We create CRM systems that help teams capture leads, manage follow-ups, track deals, and understand customer activity.',
            'features' => [
                ['icon' => 'ri-contacts-book-line', 'title' => 'Lead Management', 'text' => 'Capture, assign, tag, and track every lead from one dashboard.'],
                ['icon' => 'ri-calendar-check-line', 'title' => 'Follow-Up Flow', 'text' => 'Reminders, notes, statuses, and next-action tracking.'],
                ['icon' => 'ri-line-chart-line', 'title' => 'Pipeline Reports', 'text' => 'Sales stages, conversion visibility, and team performance summaries.'],
            ],
            'work' => [
                ['label' => 'CRM', 'name' => 'Sales Pipeline Manager', 'text' => 'Deal stages, lead assignment, and follow-up reporting.'],
                ['label' => 'Customer', 'name' => 'Contact History Hub', 'text' => 'Complete customer records with notes and interactions.'],
                ['label' => 'Reports', 'name' => 'Team Performance View', 'text' => 'Dashboards for follow-up activity and conversion tracking.'],
            ],
        ],
        'inventory-hrm' => [
            'category' => 'software',
            'title' => 'Inventory & HRM Systems',
            'headline' => 'Inventory And HRM Systems Built Around Real Business Workflows',
            'intro' => 'We build stock, purchasing, employee, attendance, payroll, and HR workflows into organized software tools.',
            'features' => [
                ['icon' => 'ri-archive-stack-line', 'title' => 'Inventory Tracking', 'text' => 'Stock levels, movement, categories, purchases, and alerts.'],
                ['icon' => 'ri-team-line', 'title' => 'Employee Records', 'text' => 'Staff profiles, attendance, payroll inputs, and department views.'],
                ['icon' => 'ri-file-chart-line', 'title' => 'Operational Reports', 'text' => 'Exports and summaries for stock, HR, and management review.'],
            ],
            'work' => [
                ['label' => 'Inventory', 'name' => 'Stock Control Panel', 'text' => 'Warehouse stock, low-stock alerts, and product movement logs.'],
                ['label' => 'HRM', 'name' => 'Employee Management Suite', 'text' => 'Staff records, attendance, and department reporting.'],
                ['label' => 'Reports', 'name' => 'Operations Summary', 'text' => 'Combined HR and inventory metrics for managers.'],
            ],
        ],
        'billing-invoicing' => [
            'category' => 'software',
            'title' => 'Billing & Invoicing Software',
            'headline' => 'Billing And Invoicing Tools That Make Payments Easier To Track',
            'intro' => 'We create invoice systems for quotations, recurring billing, receipts, payments, taxes, and customer account history.',
            'features' => [
                ['icon' => 'ri-bill-line', 'title' => 'Invoice Creation', 'text' => 'Professional invoices, quotes, receipts, and billing records.'],
                ['icon' => 'ri-money-dollar-circle-line', 'title' => 'Payment Tracking', 'text' => 'Paid, unpaid, partial, and overdue payment status views.'],
                ['icon' => 'ri-file-list-3-line', 'title' => 'Financial Reports', 'text' => 'Sales summaries, customer balances, and export-ready reports.'],
            ],
            'work' => [
                ['label' => 'Billing', 'name' => 'Invoice Dashboard', 'text' => 'Quick invoice creation with payment status tracking.'],
                ['label' => 'Payments', 'name' => 'Customer Balance View', 'text' => 'Account history and balance summary per customer.'],
                ['label' => 'Reports', 'name' => 'Monthly Revenue Export', 'text' => 'Exportable finance reports for daily and monthly review.'],
            ],
        ],
        'school-hospital-software' => [
            'category' => 'software',
            'title' => 'School / Hospital Software',
            'headline' => 'School And Hospital Software For Records, Scheduling, And Reports',
            'intro' => 'We build management systems for education and healthcare workflows, including records, appointments, departments, and reports.',
            'features' => [
                ['icon' => 'ri-hospital-line', 'title' => 'Record Management', 'text' => 'Patient, student, staff, department, and document record flows.'],
                ['icon' => 'ri-calendar-event-line', 'title' => 'Scheduling', 'text' => 'Appointments, classes, attendance, shifts, and daily planning.'],
                ['icon' => 'ri-shield-check-line', 'title' => 'Secure Access', 'text' => 'Role-based access for admins, staff, departments, and management.'],
            ],
            'work' => [
                ['label' => 'School', 'name' => 'Student Record System', 'text' => 'Admissions, classes, fees, attendance, and reports.'],
                ['label' => 'Hospital', 'name' => 'Appointment Dashboard', 'text' => 'Patient booking, department schedule, and doctor views.'],
                ['label' => 'Admin', 'name' => 'Management Reports', 'text' => 'Daily operational reports for leadership teams.'],
            ],
        ],
        'api-development' => [
            'category' => 'cloud',
            'title' => 'API Development',
            'headline' => 'API Development For Apps, Dashboards, Payments, And Integrations',
            'intro' => 'We design and build secure APIs that connect frontends, mobile apps, databases, third-party tools, and business systems.',
            'features' => [
                ['icon' => 'ri-plug-line', 'title' => 'REST APIs', 'text' => 'Clean endpoints for data, accounts, products, orders, and workflows.'],
                ['icon' => 'ri-lock-line', 'title' => 'Secure Auth', 'text' => 'Authentication, permissions, tokens, and protected access patterns.'],
                ['icon' => 'ri-file-code-line', 'title' => 'Documentation', 'text' => 'Readable API notes for developers and future maintenance.'],
            ],
            'work' => [
                ['label' => 'API', 'name' => 'Mobile App Backend', 'text' => 'Endpoints for accounts, bookings, notifications, and payments.'],
                ['label' => 'Integration', 'name' => 'Payment Gateway API', 'text' => 'Secure payment flow connected to business records.'],
                ['label' => 'Dashboard', 'name' => 'Reporting API', 'text' => 'Structured data endpoints for analytics dashboards.'],
            ],
        ],
        'database-design' => [
            'category' => 'cloud',
            'title' => 'Database Design',
            'headline' => 'Database Design That Keeps Business Data Organized And Reliable',
            'intro' => 'We plan database structures for apps, dashboards, CRMs, ERPs, ecommerce stores, and reporting systems.',
            'features' => [
                ['icon' => 'ri-database-2-line', 'title' => 'Schema Planning', 'text' => 'Tables, relationships, indexes, and data rules built for scale.'],
                ['icon' => 'ri-search-line', 'title' => 'Query Performance', 'text' => 'Data structures prepared for fast search, filtering, and reports.'],
                ['icon' => 'ri-safe-2-line', 'title' => 'Data Safety', 'text' => 'Backup planning, access control, and cleaner migration paths.'],
            ],
            'work' => [
                ['label' => 'Schema', 'name' => 'CRM Data Model', 'text' => 'Lead, customer, activity, and team relationship structure.'],
                ['label' => 'Reporting', 'name' => 'Sales Data Warehouse', 'text' => 'Organized reporting tables for business analytics.'],
                ['label' => 'Migration', 'name' => 'Legacy Data Cleanup', 'text' => 'Structured import plan for messy existing records.'],
            ],
        ],
        'cloud-hosting-setup' => [
            'category' => 'cloud',
            'title' => 'Cloud Hosting Setup',
            'headline' => 'Cloud Hosting Setup For Fast, Secure, And Manageable Websites',
            'intro' => 'We set up hosting environments, domains, SSL, deployment workflows, backups, and server configuration for digital products.',
            'features' => [
                ['icon' => 'ri-server-line', 'title' => 'Server Setup', 'text' => 'Hosting environment configured for your website or application stack.'],
                ['icon' => 'ri-shield-keyhole-line', 'title' => 'SSL And Security', 'text' => 'Domain, SSL, firewall basics, and secure access setup.'],
                ['icon' => 'ri-loop-left-line', 'title' => 'Backups', 'text' => 'Backup planning and restore-ready hosting practices.'],
            ],
            'work' => [
                ['label' => 'Cloud', 'name' => 'Business Website Hosting', 'text' => 'Secure domain, SSL, and hosting setup for a company site.'],
                ['label' => 'Deployment', 'name' => 'App Server Launch', 'text' => 'Production-ready setup for a custom web app.'],
                ['label' => 'Backup', 'name' => 'Recovery Plan', 'text' => 'Backup and restore process for active business systems.'],
            ],
        ],
        'server-deployment' => [
            'category' => 'cloud',
            'title' => 'Server Deployment',
            'headline' => 'Server Deployment For Websites, Apps, APIs, And Admin Systems',
            'intro' => 'We deploy Laravel, PHP, Node, WordPress, and custom applications with practical release, domain, and security setup.',
            'features' => [
                ['icon' => 'ri-upload-cloud-2-line', 'title' => 'Production Launch', 'text' => 'Deploy code, environment settings, database, and domains cleanly.'],
                ['icon' => 'ri-terminal-box-line', 'title' => 'Environment Setup', 'text' => 'Server packages, permissions, queues, cron jobs, and config.'],
                ['icon' => 'ri-radar-line', 'title' => 'Launch Checks', 'text' => 'Post-deploy testing for pages, forms, APIs, and performance.'],
            ],
            'work' => [
                ['label' => 'Laravel', 'name' => 'Business App Deployment', 'text' => 'Production launch with database and domain setup.'],
                ['label' => 'API', 'name' => 'Backend Release', 'text' => 'Secure API deployment with environment configuration.'],
                ['label' => 'Website', 'name' => 'CMS Deployment', 'text' => 'Server launch for editable business website.'],
            ],
        ],
        'devops-automation' => [
            'category' => 'cloud',
            'title' => 'DevOps Automation',
            'headline' => 'DevOps Automation That Makes Releases Faster And Safer',
            'intro' => 'We automate deployments, backups, testing steps, monitoring, and repeat server tasks for growing products.',
            'features' => [
                ['icon' => 'ri-git-branch-line', 'title' => 'CI/CD Pipelines', 'text' => 'Automated build and deployment flows for repeat releases.'],
                ['icon' => 'ri-alarm-warning-line', 'title' => 'Monitoring', 'text' => 'Basic alerts and checks for uptime, errors, and performance.'],
                ['icon' => 'ri-settings-5-line', 'title' => 'Repeatable Setup', 'text' => 'Cleaner deployment scripts and documentation for your team.'],
            ],
            'work' => [
                ['label' => 'Pipeline', 'name' => 'Automated Website Releases', 'text' => 'Push-to-deploy workflow for an active web product.'],
                ['label' => 'Monitoring', 'name' => 'Uptime Alert Setup', 'text' => 'Basic monitoring flow for critical business pages.'],
                ['label' => 'Operations', 'name' => 'Backup Automation', 'text' => 'Scheduled backup and restore process for production data.'],
            ],
        ],
        'ai-chatbot-integration' => [
            'category' => 'advanced',
            'title' => 'AI Chatbot Integration',
            'headline' => 'AI Chatbot Integration For Support, Leads, And Customer Guidance',
            'intro' => 'We connect chatbots to websites, support flows, FAQs, forms, and customer journeys so users get faster answers.',
            'features' => [
                ['icon' => 'ri-robot-2-line', 'title' => 'Smart Conversation Flow', 'text' => 'Helpful chatbot paths for FAQs, lead capture, and service guidance.'],
                ['icon' => 'ri-question-answer-line', 'title' => 'Knowledge Setup', 'text' => 'Business-specific answers shaped around your services and policies.'],
                ['icon' => 'ri-customer-service-2-line', 'title' => 'Handoff Flow', 'text' => 'Route complex questions to human support or inquiry forms.'],
            ],
            'work' => [
                ['label' => 'Chatbot', 'name' => 'Website Lead Assistant', 'text' => 'Bot flow that answers questions and captures new leads.'],
                ['label' => 'Support', 'name' => 'FAQ Automation', 'text' => 'Help center chatbot for repeat customer questions.'],
                ['label' => 'Sales', 'name' => 'Service Recommender', 'text' => 'Conversation flow that points users to the right package.'],
            ],
        ],
        'automation-systems' => [
            'category' => 'advanced',
            'title' => 'Automation Systems',
            'headline' => 'Automation Systems For WhatsApp, Email, Forms, And Workflows',
            'intro' => 'We automate repeat business tasks by connecting forms, messages, emails, CRMs, spreadsheets, and admin workflows.',
            'features' => [
                ['icon' => 'ri-loop-right-line', 'title' => 'Workflow Automation', 'text' => 'Trigger-based flows for lead capture, updates, and task routing.'],
                ['icon' => 'ri-whatsapp-line', 'title' => 'Messaging Flows', 'text' => 'WhatsApp, SMS, and email automations for faster follow-up.'],
                ['icon' => 'ri-links-line', 'title' => 'Tool Connections', 'text' => 'Connect forms, sheets, CRMs, payments, and internal tools.'],
            ],
            'work' => [
                ['label' => 'Leads', 'name' => 'Instant Follow-Up Flow', 'text' => 'Form submission to WhatsApp and email response automation.'],
                ['label' => 'Operations', 'name' => 'Task Routing System', 'text' => 'New requests assigned to team members automatically.'],
                ['label' => 'Admin', 'name' => 'Report Automation', 'text' => 'Daily summary data sent to management automatically.'],
            ],
        ],
        'data-analytics-dashboards' => [
            'category' => 'advanced',
            'title' => 'Data Analytics Dashboards',
            'headline' => 'Analytics Dashboards That Turn Business Data Into Clear Decisions',
            'intro' => 'We design dashboards for sales, marketing, operations, finance, and team performance using clean visual reporting.',
            'features' => [
                ['icon' => 'ri-bar-chart-2-line', 'title' => 'KPI Tracking', 'text' => 'Metrics for sales, leads, revenue, campaigns, and operations.'],
                ['icon' => 'ri-filter-3-line', 'title' => 'Smart Filters', 'text' => 'Filter by date, branch, team, service, campaign, or product.'],
                ['icon' => 'ri-pie-chart-line', 'title' => 'Visual Reports', 'text' => 'Charts, tables, and summaries that are easy to scan.'],
            ],
            'work' => [
                ['label' => 'Sales', 'name' => 'Revenue Dashboard', 'text' => 'Daily revenue, lead, and conversion reporting view.'],
                ['label' => 'Marketing', 'name' => 'Campaign Analytics', 'text' => 'Ad spend, traffic, leads, and conversion metrics in one place.'],
                ['label' => 'Operations', 'name' => 'Team Performance Board', 'text' => 'Task, activity, and department performance overview.'],
            ],
        ],
        'saas-product-development' => [
            'category' => 'advanced',
            'title' => 'SaaS Product Development',
            'headline' => 'SaaS Product Development From MVP To Scalable Platform',
            'intro' => 'We help plan, design, and build SaaS products with accounts, subscriptions, dashboards, roles, and product workflows.',
            'features' => [
                ['icon' => 'ri-rocket-line', 'title' => 'MVP Planning', 'text' => 'Prioritized feature set, product flow, and launch roadmap.'],
                ['icon' => 'ri-user-star-line', 'title' => 'Accounts And Roles', 'text' => 'Users, plans, permissions, teams, and admin management.'],
                ['icon' => 'ri-bank-card-line', 'title' => 'Subscription Flow', 'text' => 'Billing, plans, trials, payment flows, and account status logic.'],
            ],
            'work' => [
                ['label' => 'SaaS', 'name' => 'Subscription Dashboard', 'text' => 'Plan management and account screens for a SaaS MVP.'],
                ['label' => 'Product', 'name' => 'Team Workspace', 'text' => 'Multi-user workspace with roles and shared records.'],
                ['label' => 'MVP', 'name' => 'Launch-Ready Platform', 'text' => 'Core product build prepared for early users.'],
            ],
        ],
        'api-integrations' => [
            'category' => 'advanced',
            'title' => 'API Integrations',
            'headline' => 'API Integrations For Payments, SMS, WhatsApp, CRMs, And Tools',
            'intro' => 'We connect business systems with third-party APIs so data flows cleanly between apps, websites, and operations.',
            'features' => [
                ['icon' => 'ri-plug-2-line', 'title' => 'Third-Party APIs', 'text' => 'Payment, SMS, WhatsApp, email, CRM, and analytics connections.'],
                ['icon' => 'ri-exchange-line', 'title' => 'Data Sync', 'text' => 'Reliable data movement between platforms and internal dashboards.'],
                ['icon' => 'ri-error-warning-line', 'title' => 'Error Handling', 'text' => 'Clear fallbacks, logs, and alerts for integration failures.'],
            ],
            'work' => [
                ['label' => 'Payment', 'name' => 'Checkout Integration', 'text' => 'Payment status connected to customer order records.'],
                ['label' => 'Messaging', 'name' => 'WhatsApp Notifications', 'text' => 'Automated updates connected to forms and orders.'],
                ['label' => 'CRM', 'name' => 'Lead Sync Flow', 'text' => 'Website leads synced into sales pipeline automatically.'],
            ],
        ],
        'seo' => [
            'category' => 'marketing',
            'title' => 'SEO Services',
            'headline' => 'SEO Services That Help Customers Find Your Business Organically',
            'intro' => 'We improve site structure, content direction, metadata, keywords, and technical SEO basics for better search visibility.',
            'features' => [
                ['icon' => 'ri-search-line', 'title' => 'Keyword Research', 'text' => 'Practical keyword targets for your services, products, and location.'],
                ['icon' => 'ri-file-search-line', 'title' => 'On-Page SEO', 'text' => 'Titles, descriptions, headings, internal links, and content structure.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Technical Cleanup', 'text' => 'Speed, mobile, indexability, and basic crawl improvements.'],
            ],
            'work' => [
                ['label' => 'SEO', 'name' => 'Service Page Optimization', 'text' => 'Improved metadata, structure, and keyword alignment.'],
                ['label' => 'Local', 'name' => 'Local Search Setup', 'text' => 'Location-focused improvements for service visibility.'],
                ['label' => 'Technical', 'name' => 'SEO Health Fixes', 'text' => 'Cleaned crawl issues and improved page performance signals.'],
            ],
        ],
        'social-media-marketing' => [
            'category' => 'marketing',
            'title' => 'Social Media Marketing',
            'headline' => 'Social Media Marketing That Builds Awareness And Converts Attention',
            'intro' => 'We plan campaigns, content calendars, creative direction, and performance tracking for active social channels.',
            'features' => [
                ['icon' => 'ri-calendar-todo-line', 'title' => 'Content Calendar', 'text' => 'Planned posts for offers, education, testimonials, and promotions.'],
                ['icon' => 'ri-image-line', 'title' => 'Creative Direction', 'text' => 'Post visuals, captions, themes, and campaign asset planning.'],
                ['icon' => 'ri-line-chart-line', 'title' => 'Performance Reports', 'text' => 'Reach, engagement, clicks, leads, and improvement notes.'],
            ],
            'work' => [
                ['label' => 'Instagram', 'name' => 'Monthly Growth Plan', 'text' => 'Content calendar and creative system for a local brand.'],
                ['label' => 'Campaign', 'name' => 'Launch Awareness Push', 'text' => 'Social campaign for a new service launch.'],
                ['label' => 'Reports', 'name' => 'Engagement Dashboard', 'text' => 'Monthly social results and optimization direction.'],
            ],
        ],
        'google-ads-ppc' => [
            'category' => 'marketing',
            'title' => 'Google Ads / PPC',
            'headline' => 'Google Ads And PPC Campaigns Built Around Leads And Sales',
            'intro' => 'We create paid search campaigns, ad groups, landing page direction, tracking setup, and performance optimization plans.',
            'features' => [
                ['icon' => 'ri-advertisement-line', 'title' => 'Campaign Setup', 'text' => 'Search campaigns structured around keywords, services, and goals.'],
                ['icon' => 'ri-focus-3-line', 'title' => 'Conversion Tracking', 'text' => 'Track form submissions, calls, clicks, and important actions.'],
                ['icon' => 'ri-funds-line', 'title' => 'Budget Optimization', 'text' => 'Ongoing tuning for spend, targeting, ad copy, and landing pages.'],
            ],
            'work' => [
                ['label' => 'PPC', 'name' => 'Lead Generation Campaign', 'text' => 'Search ads and tracking flow for service inquiries.'],
                ['label' => 'Landing', 'name' => 'Ad Landing Page', 'text' => 'Focused landing page for paid traffic conversion.'],
                ['label' => 'Tracking', 'name' => 'Conversion Setup', 'text' => 'Form and call tracking connected to campaign reporting.'],
            ],
        ],
        'content-marketing' => [
            'category' => 'marketing',
            'title' => 'Content Marketing',
            'headline' => 'Content Marketing That Educates Customers And Supports Search Growth',
            'intro' => 'We plan useful content for blogs, landing pages, campaigns, FAQs, and service pages that support customer trust.',
            'features' => [
                ['icon' => 'ri-article-line', 'title' => 'Content Strategy', 'text' => 'Topics and structure based on customer questions and search intent.'],
                ['icon' => 'ri-edit-line', 'title' => 'Page Copy Direction', 'text' => 'Clear content flows for services, offers, and conversion pages.'],
                ['icon' => 'ri-book-open-line', 'title' => 'Educational Assets', 'text' => 'Guides, FAQs, blog outlines, and reusable content ideas.'],
            ],
            'work' => [
                ['label' => 'Blog', 'name' => 'Industry Topic Plan', 'text' => 'Search-aligned content calendar for service visibility.'],
                ['label' => 'Landing', 'name' => 'Offer Page Copy', 'text' => 'Conversion-focused content flow for a campaign.'],
                ['label' => 'FAQ', 'name' => 'Customer Answer Library', 'text' => 'Helpful answers structured for support and SEO.'],
            ],
        ],
        'email-campaigns' => [
            'category' => 'marketing',
            'title' => 'Email Campaigns',
            'headline' => 'Email Campaigns That Keep Leads And Customers Moving',
            'intro' => 'We design email sequences, newsletters, offers, follow-ups, and automations that support sales and customer retention.',
            'features' => [
                ['icon' => 'ri-mail-send-line', 'title' => 'Email Sequences', 'text' => 'Welcome, lead nurture, offer, and follow-up campaign flows.'],
                ['icon' => 'ri-layout-row-line', 'title' => 'Newsletter Design', 'text' => 'Readable email layouts for announcements, tips, and updates.'],
                ['icon' => 'ri-bar-chart-grouped-line', 'title' => 'Campaign Tracking', 'text' => 'Open, click, response, and conversion performance review.'],
            ],
            'work' => [
                ['label' => 'Newsletter', 'name' => 'Monthly Customer Email', 'text' => 'Branded newsletter layout for repeat audience engagement.'],
                ['label' => 'Nurture', 'name' => 'Lead Follow-Up Flow', 'text' => 'Automated email sequence after website inquiries.'],
                ['label' => 'Sales', 'name' => 'Offer Campaign', 'text' => 'Promotion email set with clear call to action.'],
            ],
        ],
        'graphic-creative' => [
            'category' => 'creative',
            'title' => 'Graphic & Creative Design',
            'headline' => 'Graphic And Creative Assets For Campaigns, Posts, Decks, And Launches',
            'intro' => 'We create banners, flyers, thumbnails, presentations, mockups, and campaign graphics for everyday marketing needs.',
            'features' => [
                ['icon' => 'ri-image-line', 'title' => 'Campaign Graphics', 'text' => 'Posters, flyers, thumbnails, banners, and ad visuals.'],
                ['icon' => 'ri-slideshow-line', 'title' => 'Presentation Design', 'text' => 'Polished slides for company profiles, pitches, and reports.'],
                ['icon' => 'ri-video-line', 'title' => 'Motion Direction', 'text' => 'Simple video editing and motion graphic concepts for campaigns.'],
            ],
            'work' => [
                ['label' => 'Creative', 'name' => 'Campaign Asset Pack', 'text' => 'Static graphics for ads, social posts, and promotions.'],
                ['label' => 'Deck', 'name' => 'Company Presentation', 'text' => 'Branded presentation design for a business pitch.'],
                ['label' => 'Thumbnail', 'name' => 'Video Content Kit', 'text' => 'YouTube and social video thumbnail designs.'],
            ],
        ],
        'maintenance-support' => [
            'category' => 'support',
            'title' => 'Maintenance & Support',
            'headline' => 'Maintenance And Support For Websites, Apps, And Business Systems',
            'intro' => 'We keep digital platforms updated, secure, backed up, and performing well with practical ongoing support plans.',
            'features' => [
                ['icon' => 'ri-bug-line', 'title' => 'Bug Fixes', 'text' => 'Resolve layout, form, data, and functional issues quickly.'],
                ['icon' => 'ri-shield-check-line', 'title' => 'Security Updates', 'text' => 'Patch, update, and protect active websites and systems.'],
                ['icon' => 'ri-speed-up-line', 'title' => 'Performance Care', 'text' => 'Optimize speed, backups, and stability after launch.'],
            ],
            'work' => [
                ['label' => 'Support', 'name' => 'Website Care Plan', 'text' => 'Monthly updates, checks, and issue resolution.'],
                ['label' => 'Security', 'name' => 'Patch And Backup Setup', 'text' => 'Safer update process with backup protection.'],
                ['label' => 'Performance', 'name' => 'Speed Improvement Sprint', 'text' => 'Cleanup and optimization for faster page loading.'],
            ],
        ],
    ],
];
